// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/wrappers.proto

package com.google.protobuf;

public interface BytesValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.BytesValue)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * The bytes value.
   * </pre>
   *
   * <code>optional bytes value = 1;</code>
   */
  com.google.protobuf.ByteString getValue();
}
