// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/type.proto

package com.google.protobuf;

/**
 * <pre>
 * Enum type definition.
 * </pre>
 *
 * Protobuf type {@code google.protobuf.Enum}
 */
public  final class Enum extends
    com.google.protobuf.GeneratedMessageLite<
        Enum, Enum.Builder> implements
    // @@protoc_insertion_point(message_implements:google.protobuf.Enum)
    EnumOrBuilder {
  private Enum() {
    name_ = "";
    enumvalue_ = emptyProtobufList();
    options_ = emptyProtobufList();
  }
  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  private java.lang.String name_;
  /**
   * <pre>
   * Enum type name.
   * </pre>
   *
   * <code>optional string name = 1;</code>
   */
  public java.lang.String getName() {
    return name_;
  }
  /**
   * <pre>
   * Enum type name.
   * </pre>
   *
   * <code>optional string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(name_);
  }
  /**
   * <pre>
   * Enum type name.
   * </pre>
   *
   * <code>optional string name = 1;</code>
   */
  private void setName(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    name_ = value;
  }
  /**
   * <pre>
   * Enum type name.
   * </pre>
   *
   * <code>optional string name = 1;</code>
   */
  private void clearName() {
    
    name_ = getDefaultInstance().getName();
  }
  /**
   * <pre>
   * Enum type name.
   * </pre>
   *
   * <code>optional string name = 1;</code>
   */
  private void setNameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    name_ = value.toStringUtf8();
  }

  public static final int ENUMVALUE_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.EnumValue> enumvalue_;
  /**
   * <pre>
   * Enum value definitions.
   * </pre>
   *
   * <code>repeated .google.protobuf.EnumValue enumvalue = 2;</code>
   */
  public java.util.List<com.google.protobuf.EnumValue> getEnumvalueList() {
    return enumvalue_;
  }
  /**
   * <pre>
   * Enum value definitions.
   * </pre>
   *
   * <code>repeated .google.protobuf.EnumValue enumvalue = 2;</code>
   */
  public java.util.List<? extends com.google.protobuf.EnumValueOrBuilder> 
      getEnumvalueOrBuilderList() {
    return enumvalue_;
  }
  /**
   * <pre>
   * Enum value definitions.
   * </pre>
   *
   * <code>repeated .google.protobuf.EnumValue enumvalue = 2;</code>
   */
  public int getEnumvalueCount() {
    return enumvalue_.size();
  }
  /**
   * <pre>
   * Enum value definitions.
   * </pre>
   *
   * <code>repeated .google.protobuf.EnumValue enumvalue = 2;</code>
   */
  public com.google.protobuf.EnumValue getEnumvalue(int index) {
    return enumvalue_.get(index);
  }
  /**
   * <pre>
   * Enum value definitions.
   * </pre>
   *
   * <code>repeated .google.protobuf.EnumValue enumvalue = 2;</code>
   */
  public com.google.protobuf.EnumValueOrBuilder getEnumvalueOrBuilder(
      int index) {
    return enumvalue_.get(index);
  }
  private void ensureEnumvalueIsMutable() {
    if (!enumvalue_.isModifiable()) {
      enumvalue_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(enumvalue_);
     }
  }

  /**
   * <pre>
   * Enum value definitions.
   * </pre>
   *
   * <code>repeated .google.protobuf.EnumValue enumvalue = 2;</code>
   */
  private void setEnumvalue(
      int index, com.google.protobuf.EnumValue value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureEnumvalueIsMutable();
    enumvalue_.set(index, value);
  }
  /**
   * <pre>
   * Enum value definitions.
   * </pre>
   *
   * <code>repeated .google.protobuf.EnumValue enumvalue = 2;</code>
   */
  private void setEnumvalue(
      int index, com.google.protobuf.EnumValue.Builder builderForValue) {
    ensureEnumvalueIsMutable();
    enumvalue_.set(index, builderForValue.build());
  }
  /**
   * <pre>
   * Enum value definitions.
   * </pre>
   *
   * <code>repeated .google.protobuf.EnumValue enumvalue = 2;</code>
   */
  private void addEnumvalue(com.google.protobuf.EnumValue value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureEnumvalueIsMutable();
    enumvalue_.add(value);
  }
  /**
   * <pre>
   * Enum value definitions.
   * </pre>
   *
   * <code>repeated .google.protobuf.EnumValue enumvalue = 2;</code>
   */
  private void addEnumvalue(
      int index, com.google.protobuf.EnumValue value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureEnumvalueIsMutable();
    enumvalue_.add(index, value);
  }
  /**
   * <pre>
   * Enum value definitions.
   * </pre>
   *
   * <code>repeated .google.protobuf.EnumValue enumvalue = 2;</code>
   */
  private void addEnumvalue(
      com.google.protobuf.EnumValue.Builder builderForValue) {
    ensureEnumvalueIsMutable();
    enumvalue_.add(builderForValue.build());
  }
  /**
   * <pre>
   * Enum value definitions.
   * </pre>
   *
   * <code>repeated .google.protobuf.EnumValue enumvalue = 2;</code>
   */
  private void addEnumvalue(
      int index, com.google.protobuf.EnumValue.Builder builderForValue) {
    ensureEnumvalueIsMutable();
    enumvalue_.add(index, builderForValue.build());
  }
  /**
   * <pre>
   * Enum value definitions.
   * </pre>
   *
   * <code>repeated .google.protobuf.EnumValue enumvalue = 2;</code>
   */
  private void addAllEnumvalue(
      java.lang.Iterable<? extends com.google.protobuf.EnumValue> values) {
    ensureEnumvalueIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, enumvalue_);
  }
  /**
   * <pre>
   * Enum value definitions.
   * </pre>
   *
   * <code>repeated .google.protobuf.EnumValue enumvalue = 2;</code>
   */
  private void clearEnumvalue() {
    enumvalue_ = emptyProtobufList();
  }
  /**
   * <pre>
   * Enum value definitions.
   * </pre>
   *
   * <code>repeated .google.protobuf.EnumValue enumvalue = 2;</code>
   */
  private void removeEnumvalue(int index) {
    ensureEnumvalueIsMutable();
    enumvalue_.remove(index);
  }

  public static final int OPTIONS_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.Option> options_;
  /**
   * <pre>
   * Protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 3;</code>
   */
  public java.util.List<com.google.protobuf.Option> getOptionsList() {
    return options_;
  }
  /**
   * <pre>
   * Protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 3;</code>
   */
  public java.util.List<? extends com.google.protobuf.OptionOrBuilder> 
      getOptionsOrBuilderList() {
    return options_;
  }
  /**
   * <pre>
   * Protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 3;</code>
   */
  public int getOptionsCount() {
    return options_.size();
  }
  /**
   * <pre>
   * Protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 3;</code>
   */
  public com.google.protobuf.Option getOptions(int index) {
    return options_.get(index);
  }
  /**
   * <pre>
   * Protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 3;</code>
   */
  public com.google.protobuf.OptionOrBuilder getOptionsOrBuilder(
      int index) {
    return options_.get(index);
  }
  private void ensureOptionsIsMutable() {
    if (!options_.isModifiable()) {
      options_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(options_);
     }
  }

  /**
   * <pre>
   * Protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 3;</code>
   */
  private void setOptions(
      int index, com.google.protobuf.Option value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureOptionsIsMutable();
    options_.set(index, value);
  }
  /**
   * <pre>
   * Protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 3;</code>
   */
  private void setOptions(
      int index, com.google.protobuf.Option.Builder builderForValue) {
    ensureOptionsIsMutable();
    options_.set(index, builderForValue.build());
  }
  /**
   * <pre>
   * Protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 3;</code>
   */
  private void addOptions(com.google.protobuf.Option value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureOptionsIsMutable();
    options_.add(value);
  }
  /**
   * <pre>
   * Protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 3;</code>
   */
  private void addOptions(
      int index, com.google.protobuf.Option value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureOptionsIsMutable();
    options_.add(index, value);
  }
  /**
   * <pre>
   * Protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 3;</code>
   */
  private void addOptions(
      com.google.protobuf.Option.Builder builderForValue) {
    ensureOptionsIsMutable();
    options_.add(builderForValue.build());
  }
  /**
   * <pre>
   * Protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 3;</code>
   */
  private void addOptions(
      int index, com.google.protobuf.Option.Builder builderForValue) {
    ensureOptionsIsMutable();
    options_.add(index, builderForValue.build());
  }
  /**
   * <pre>
   * Protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 3;</code>
   */
  private void addAllOptions(
      java.lang.Iterable<? extends com.google.protobuf.Option> values) {
    ensureOptionsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, options_);
  }
  /**
   * <pre>
   * Protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 3;</code>
   */
  private void clearOptions() {
    options_ = emptyProtobufList();
  }
  /**
   * <pre>
   * Protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 3;</code>
   */
  private void removeOptions(int index) {
    ensureOptionsIsMutable();
    options_.remove(index);
  }

  public static final int SOURCE_CONTEXT_FIELD_NUMBER = 4;
  private com.google.protobuf.SourceContext sourceContext_;
  /**
   * <pre>
   * The source context.
   * </pre>
   *
   * <code>optional .google.protobuf.SourceContext source_context = 4;</code>
   */
  public boolean hasSourceContext() {
    return sourceContext_ != null;
  }
  /**
   * <pre>
   * The source context.
   * </pre>
   *
   * <code>optional .google.protobuf.SourceContext source_context = 4;</code>
   */
  public com.google.protobuf.SourceContext getSourceContext() {
    return sourceContext_ == null ? com.google.protobuf.SourceContext.getDefaultInstance() : sourceContext_;
  }
  /**
   * <pre>
   * The source context.
   * </pre>
   *
   * <code>optional .google.protobuf.SourceContext source_context = 4;</code>
   */
  private void setSourceContext(com.google.protobuf.SourceContext value) {
    if (value == null) {
      throw new NullPointerException();
    }
    sourceContext_ = value;
    
    }
  /**
   * <pre>
   * The source context.
   * </pre>
   *
   * <code>optional .google.protobuf.SourceContext source_context = 4;</code>
   */
  private void setSourceContext(
      com.google.protobuf.SourceContext.Builder builderForValue) {
    sourceContext_ = builderForValue.build();
    
  }
  /**
   * <pre>
   * The source context.
   * </pre>
   *
   * <code>optional .google.protobuf.SourceContext source_context = 4;</code>
   */
  private void mergeSourceContext(com.google.protobuf.SourceContext value) {
    if (sourceContext_ != null &&
        sourceContext_ != com.google.protobuf.SourceContext.getDefaultInstance()) {
      sourceContext_ =
        com.google.protobuf.SourceContext.newBuilder(sourceContext_).mergeFrom(value).buildPartial();
    } else {
      sourceContext_ = value;
    }
    
  }
  /**
   * <pre>
   * The source context.
   * </pre>
   *
   * <code>optional .google.protobuf.SourceContext source_context = 4;</code>
   */
  private void clearSourceContext() {  sourceContext_ = null;
    
  }

  public static final int SYNTAX_FIELD_NUMBER = 5;
  private int syntax_;
  /**
   * <pre>
   * The source syntax.
   * </pre>
   *
   * <code>optional .google.protobuf.Syntax syntax = 5;</code>
   */
  public int getSyntaxValue() {
    return syntax_;
  }
  /**
   * <pre>
   * The source syntax.
   * </pre>
   *
   * <code>optional .google.protobuf.Syntax syntax = 5;</code>
   */
  public com.google.protobuf.Syntax getSyntax() {
    com.google.protobuf.Syntax result = com.google.protobuf.Syntax.forNumber(syntax_);
    return result == null ? com.google.protobuf.Syntax.UNRECOGNIZED : result;
  }
  /**
   * <pre>
   * The source syntax.
   * </pre>
   *
   * <code>optional .google.protobuf.Syntax syntax = 5;</code>
   */
  private void setSyntaxValue(int value) {
      syntax_ = value;
  }
  /**
   * <pre>
   * The source syntax.
   * </pre>
   *
   * <code>optional .google.protobuf.Syntax syntax = 5;</code>
   */
  private void setSyntax(com.google.protobuf.Syntax value) {
    if (value == null) {
      throw new NullPointerException();
    }
    
    syntax_ = value.getNumber();
  }
  /**
   * <pre>
   * The source syntax.
   * </pre>
   *
   * <code>optional .google.protobuf.Syntax syntax = 5;</code>
   */
  private void clearSyntax() {
    
    syntax_ = 0;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!name_.isEmpty()) {
      output.writeString(1, getName());
    }
    for (int i = 0; i < enumvalue_.size(); i++) {
      output.writeMessage(2, enumvalue_.get(i));
    }
    for (int i = 0; i < options_.size(); i++) {
      output.writeMessage(3, options_.get(i));
    }
    if (sourceContext_ != null) {
      output.writeMessage(4, getSourceContext());
    }
    if (syntax_ != com.google.protobuf.Syntax.SYNTAX_PROTO2.getNumber()) {
      output.writeEnum(5, syntax_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!name_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getName());
    }
    for (int i = 0; i < enumvalue_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, enumvalue_.get(i));
    }
    for (int i = 0; i < options_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, options_.get(i));
    }
    if (sourceContext_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getSourceContext());
    }
    if (syntax_ != com.google.protobuf.Syntax.SYNTAX_PROTO2.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, syntax_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static com.google.protobuf.Enum parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.protobuf.Enum parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.protobuf.Enum parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.protobuf.Enum parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.protobuf.Enum parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.protobuf.Enum parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.protobuf.Enum parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.google.protobuf.Enum parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.protobuf.Enum parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.protobuf.Enum parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.protobuf.Enum prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * <pre>
   * Enum type definition.
   * </pre>
   *
   * Protobuf type {@code google.protobuf.Enum}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.google.protobuf.Enum, Builder> implements
      // @@protoc_insertion_point(builder_implements:google.protobuf.Enum)
      com.google.protobuf.EnumOrBuilder {
    // Construct using com.google.protobuf.Enum.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * Enum type name.
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      return instance.getName();
    }
    /**
     * <pre>
     * Enum type name.
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      return instance.getNameBytes();
    }
    /**
     * <pre>
     * Enum type name.
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      copyOnWrite();
      instance.setName(value);
      return this;
    }
    /**
     * <pre>
     * Enum type name.
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    public Builder clearName() {
      copyOnWrite();
      instance.clearName();
      return this;
    }
    /**
     * <pre>
     * Enum type name.
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameBytes(value);
      return this;
    }

    /**
     * <pre>
     * Enum value definitions.
     * </pre>
     *
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2;</code>
     */
    public java.util.List<com.google.protobuf.EnumValue> getEnumvalueList() {
      return java.util.Collections.unmodifiableList(
          instance.getEnumvalueList());
    }
    /**
     * <pre>
     * Enum value definitions.
     * </pre>
     *
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2;</code>
     */
    public int getEnumvalueCount() {
      return instance.getEnumvalueCount();
    }/**
     * <pre>
     * Enum value definitions.
     * </pre>
     *
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2;</code>
     */
    public com.google.protobuf.EnumValue getEnumvalue(int index) {
      return instance.getEnumvalue(index);
    }
    /**
     * <pre>
     * Enum value definitions.
     * </pre>
     *
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2;</code>
     */
    public Builder setEnumvalue(
        int index, com.google.protobuf.EnumValue value) {
      copyOnWrite();
      instance.setEnumvalue(index, value);
      return this;
    }
    /**
     * <pre>
     * Enum value definitions.
     * </pre>
     *
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2;</code>
     */
    public Builder setEnumvalue(
        int index, com.google.protobuf.EnumValue.Builder builderForValue) {
      copyOnWrite();
      instance.setEnumvalue(index, builderForValue);
      return this;
    }
    /**
     * <pre>
     * Enum value definitions.
     * </pre>
     *
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2;</code>
     */
    public Builder addEnumvalue(com.google.protobuf.EnumValue value) {
      copyOnWrite();
      instance.addEnumvalue(value);
      return this;
    }
    /**
     * <pre>
     * Enum value definitions.
     * </pre>
     *
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2;</code>
     */
    public Builder addEnumvalue(
        int index, com.google.protobuf.EnumValue value) {
      copyOnWrite();
      instance.addEnumvalue(index, value);
      return this;
    }
    /**
     * <pre>
     * Enum value definitions.
     * </pre>
     *
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2;</code>
     */
    public Builder addEnumvalue(
        com.google.protobuf.EnumValue.Builder builderForValue) {
      copyOnWrite();
      instance.addEnumvalue(builderForValue);
      return this;
    }
    /**
     * <pre>
     * Enum value definitions.
     * </pre>
     *
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2;</code>
     */
    public Builder addEnumvalue(
        int index, com.google.protobuf.EnumValue.Builder builderForValue) {
      copyOnWrite();
      instance.addEnumvalue(index, builderForValue);
      return this;
    }
    /**
     * <pre>
     * Enum value definitions.
     * </pre>
     *
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2;</code>
     */
    public Builder addAllEnumvalue(
        java.lang.Iterable<? extends com.google.protobuf.EnumValue> values) {
      copyOnWrite();
      instance.addAllEnumvalue(values);
      return this;
    }
    /**
     * <pre>
     * Enum value definitions.
     * </pre>
     *
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2;</code>
     */
    public Builder clearEnumvalue() {
      copyOnWrite();
      instance.clearEnumvalue();
      return this;
    }
    /**
     * <pre>
     * Enum value definitions.
     * </pre>
     *
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2;</code>
     */
    public Builder removeEnumvalue(int index) {
      copyOnWrite();
      instance.removeEnumvalue(index);
      return this;
    }

    /**
     * <pre>
     * Protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    public java.util.List<com.google.protobuf.Option> getOptionsList() {
      return java.util.Collections.unmodifiableList(
          instance.getOptionsList());
    }
    /**
     * <pre>
     * Protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    public int getOptionsCount() {
      return instance.getOptionsCount();
    }/**
     * <pre>
     * Protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    public com.google.protobuf.Option getOptions(int index) {
      return instance.getOptions(index);
    }
    /**
     * <pre>
     * Protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    public Builder setOptions(
        int index, com.google.protobuf.Option value) {
      copyOnWrite();
      instance.setOptions(index, value);
      return this;
    }
    /**
     * <pre>
     * Protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    public Builder setOptions(
        int index, com.google.protobuf.Option.Builder builderForValue) {
      copyOnWrite();
      instance.setOptions(index, builderForValue);
      return this;
    }
    /**
     * <pre>
     * Protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    public Builder addOptions(com.google.protobuf.Option value) {
      copyOnWrite();
      instance.addOptions(value);
      return this;
    }
    /**
     * <pre>
     * Protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    public Builder addOptions(
        int index, com.google.protobuf.Option value) {
      copyOnWrite();
      instance.addOptions(index, value);
      return this;
    }
    /**
     * <pre>
     * Protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    public Builder addOptions(
        com.google.protobuf.Option.Builder builderForValue) {
      copyOnWrite();
      instance.addOptions(builderForValue);
      return this;
    }
    /**
     * <pre>
     * Protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    public Builder addOptions(
        int index, com.google.protobuf.Option.Builder builderForValue) {
      copyOnWrite();
      instance.addOptions(index, builderForValue);
      return this;
    }
    /**
     * <pre>
     * Protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    public Builder addAllOptions(
        java.lang.Iterable<? extends com.google.protobuf.Option> values) {
      copyOnWrite();
      instance.addAllOptions(values);
      return this;
    }
    /**
     * <pre>
     * Protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    public Builder clearOptions() {
      copyOnWrite();
      instance.clearOptions();
      return this;
    }
    /**
     * <pre>
     * Protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 3;</code>
     */
    public Builder removeOptions(int index) {
      copyOnWrite();
      instance.removeOptions(index);
      return this;
    }

    /**
     * <pre>
     * The source context.
     * </pre>
     *
     * <code>optional .google.protobuf.SourceContext source_context = 4;</code>
     */
    public boolean hasSourceContext() {
      return instance.hasSourceContext();
    }
    /**
     * <pre>
     * The source context.
     * </pre>
     *
     * <code>optional .google.protobuf.SourceContext source_context = 4;</code>
     */
    public com.google.protobuf.SourceContext getSourceContext() {
      return instance.getSourceContext();
    }
    /**
     * <pre>
     * The source context.
     * </pre>
     *
     * <code>optional .google.protobuf.SourceContext source_context = 4;</code>
     */
    public Builder setSourceContext(com.google.protobuf.SourceContext value) {
      copyOnWrite();
      instance.setSourceContext(value);
      return this;
      }
    /**
     * <pre>
     * The source context.
     * </pre>
     *
     * <code>optional .google.protobuf.SourceContext source_context = 4;</code>
     */
    public Builder setSourceContext(
        com.google.protobuf.SourceContext.Builder builderForValue) {
      copyOnWrite();
      instance.setSourceContext(builderForValue);
      return this;
    }
    /**
     * <pre>
     * The source context.
     * </pre>
     *
     * <code>optional .google.protobuf.SourceContext source_context = 4;</code>
     */
    public Builder mergeSourceContext(com.google.protobuf.SourceContext value) {
      copyOnWrite();
      instance.mergeSourceContext(value);
      return this;
    }
    /**
     * <pre>
     * The source context.
     * </pre>
     *
     * <code>optional .google.protobuf.SourceContext source_context = 4;</code>
     */
    public Builder clearSourceContext() {  copyOnWrite();
      instance.clearSourceContext();
      return this;
    }

    /**
     * <pre>
     * The source syntax.
     * </pre>
     *
     * <code>optional .google.protobuf.Syntax syntax = 5;</code>
     */
    public int getSyntaxValue() {
      return instance.getSyntaxValue();
    }
    /**
     * <pre>
     * The source syntax.
     * </pre>
     *
     * <code>optional .google.protobuf.Syntax syntax = 5;</code>
     */
    public Builder setSyntaxValue(int value) {
      copyOnWrite();
      instance.setSyntaxValue(value);
      return this;
    }
    /**
     * <pre>
     * The source syntax.
     * </pre>
     *
     * <code>optional .google.protobuf.Syntax syntax = 5;</code>
     */
    public com.google.protobuf.Syntax getSyntax() {
      return instance.getSyntax();
    }
    /**
     * <pre>
     * The source syntax.
     * </pre>
     *
     * <code>optional .google.protobuf.Syntax syntax = 5;</code>
     */
    public Builder setSyntax(com.google.protobuf.Syntax value) {
      copyOnWrite();
      instance.setSyntax(value);
      return this;
    }
    /**
     * <pre>
     * The source syntax.
     * </pre>
     *
     * <code>optional .google.protobuf.Syntax syntax = 5;</code>
     */
    public Builder clearSyntax() {
      copyOnWrite();
      instance.clearSyntax();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.protobuf.Enum)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.google.protobuf.Enum();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        enumvalue_.makeImmutable();
        options_.makeImmutable();
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        com.google.protobuf.Enum other = (com.google.protobuf.Enum) arg1;
        name_ = visitor.visitString(!name_.isEmpty(), name_,
            !other.name_.isEmpty(), other.name_);
        enumvalue_= visitor.visitList(enumvalue_, other.enumvalue_);
        options_= visitor.visitList(options_, other.options_);
        sourceContext_ = visitor.visitMessage(sourceContext_, other.sourceContext_);
        syntax_ = visitor.visitInt(syntax_ != 0, syntax_,    other.syntax_ != 0, other.syntax_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
              case 18: {
                if (!enumvalue_.isModifiable()) {
                  enumvalue_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(enumvalue_);
                }
                enumvalue_.add(
                    input.readMessage(com.google.protobuf.EnumValue.parser(), extensionRegistry));
                break;
              }
              case 26: {
                if (!options_.isModifiable()) {
                  options_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(options_);
                }
                options_.add(
                    input.readMessage(com.google.protobuf.Option.parser(), extensionRegistry));
                break;
              }
              case 34: {
                com.google.protobuf.SourceContext.Builder subBuilder = null;
                if (sourceContext_ != null) {
                  subBuilder = sourceContext_.toBuilder();
                }
                sourceContext_ = input.readMessage(com.google.protobuf.SourceContext.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(sourceContext_);
                  sourceContext_ = subBuilder.buildPartial();
                }

                break;
              }
              case 40: {
                int rawValue = input.readEnum();

                syntax_ = rawValue;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (com.google.protobuf.Enum.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:google.protobuf.Enum)
  private static final com.google.protobuf.Enum DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Enum();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static com.google.protobuf.Enum getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Enum> PARSER;

  public static com.google.protobuf.Parser<Enum> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

