// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/type.proto

package com.google.protobuf;

public interface EnumOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.Enum)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Enum type name.
   * </pre>
   *
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * Enum type name.
   * </pre>
   *
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Enum value definitions.
   * </pre>
   *
   * <code>repeated .google.protobuf.EnumValue enumvalue = 2;</code>
   */
  java.util.List<com.google.protobuf.EnumValue> 
      getEnumvalueList();
  /**
   * <pre>
   * Enum value definitions.
   * </pre>
   *
   * <code>repeated .google.protobuf.EnumValue enumvalue = 2;</code>
   */
  com.google.protobuf.EnumValue getEnumvalue(int index);
  /**
   * <pre>
   * Enum value definitions.
   * </pre>
   *
   * <code>repeated .google.protobuf.EnumValue enumvalue = 2;</code>
   */
  int getEnumvalueCount();

  /**
   * <pre>
   * Protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 3;</code>
   */
  java.util.List<com.google.protobuf.Option> 
      getOptionsList();
  /**
   * <pre>
   * Protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 3;</code>
   */
  com.google.protobuf.Option getOptions(int index);
  /**
   * <pre>
   * Protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 3;</code>
   */
  int getOptionsCount();

  /**
   * <pre>
   * The source context.
   * </pre>
   *
   * <code>optional .google.protobuf.SourceContext source_context = 4;</code>
   */
  boolean hasSourceContext();
  /**
   * <pre>
   * The source context.
   * </pre>
   *
   * <code>optional .google.protobuf.SourceContext source_context = 4;</code>
   */
  com.google.protobuf.SourceContext getSourceContext();

  /**
   * <pre>
   * The source syntax.
   * </pre>
   *
   * <code>optional .google.protobuf.Syntax syntax = 5;</code>
   */
  int getSyntaxValue();
  /**
   * <pre>
   * The source syntax.
   * </pre>
   *
   * <code>optional .google.protobuf.Syntax syntax = 5;</code>
   */
  com.google.protobuf.Syntax getSyntax();
}
