// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/type.proto

package com.google.protobuf;

/**
 * <pre>
 * A single field of a message type.
 * </pre>
 *
 * Protobuf type {@code google.protobuf.Field}
 */
public  final class Field extends
    com.google.protobuf.GeneratedMessageLite<
        Field, Field.Builder> implements
    // @@protoc_insertion_point(message_implements:google.protobuf.Field)
    FieldOrBuilder {
  private Field() {
    name_ = "";
    typeUrl_ = "";
    options_ = emptyProtobufList();
    jsonName_ = "";
    defaultValue_ = "";
  }
  /**
   * <pre>
   * Basic field types.
   * </pre>
   *
   * Protobuf enum {@code google.protobuf.Field.Kind}
   */
  public enum Kind
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <pre>
     * Field type unknown.
     * </pre>
     *
     * <code>TYPE_UNKNOWN = 0;</code>
     */
    TYPE_UNKNOWN(0),
    /**
     * <pre>
     * Field type double.
     * </pre>
     *
     * <code>TYPE_DOUBLE = 1;</code>
     */
    TYPE_DOUBLE(1),
    /**
     * <pre>
     * Field type float.
     * </pre>
     *
     * <code>TYPE_FLOAT = 2;</code>
     */
    TYPE_FLOAT(2),
    /**
     * <pre>
     * Field type int64.
     * </pre>
     *
     * <code>TYPE_INT64 = 3;</code>
     */
    TYPE_INT64(3),
    /**
     * <pre>
     * Field type uint64.
     * </pre>
     *
     * <code>TYPE_UINT64 = 4;</code>
     */
    TYPE_UINT64(4),
    /**
     * <pre>
     * Field type int32.
     * </pre>
     *
     * <code>TYPE_INT32 = 5;</code>
     */
    TYPE_INT32(5),
    /**
     * <pre>
     * Field type fixed64.
     * </pre>
     *
     * <code>TYPE_FIXED64 = 6;</code>
     */
    TYPE_FIXED64(6),
    /**
     * <pre>
     * Field type fixed32.
     * </pre>
     *
     * <code>TYPE_FIXED32 = 7;</code>
     */
    TYPE_FIXED32(7),
    /**
     * <pre>
     * Field type bool.
     * </pre>
     *
     * <code>TYPE_BOOL = 8;</code>
     */
    TYPE_BOOL(8),
    /**
     * <pre>
     * Field type string.
     * </pre>
     *
     * <code>TYPE_STRING = 9;</code>
     */
    TYPE_STRING(9),
    /**
     * <pre>
     * Field type group. Proto2 syntax only, and deprecated.
     * </pre>
     *
     * <code>TYPE_GROUP = 10;</code>
     */
    TYPE_GROUP(10),
    /**
     * <pre>
     * Field type message.
     * </pre>
     *
     * <code>TYPE_MESSAGE = 11;</code>
     */
    TYPE_MESSAGE(11),
    /**
     * <pre>
     * Field type bytes.
     * </pre>
     *
     * <code>TYPE_BYTES = 12;</code>
     */
    TYPE_BYTES(12),
    /**
     * <pre>
     * Field type uint32.
     * </pre>
     *
     * <code>TYPE_UINT32 = 13;</code>
     */
    TYPE_UINT32(13),
    /**
     * <pre>
     * Field type enum.
     * </pre>
     *
     * <code>TYPE_ENUM = 14;</code>
     */
    TYPE_ENUM(14),
    /**
     * <pre>
     * Field type sfixed32.
     * </pre>
     *
     * <code>TYPE_SFIXED32 = 15;</code>
     */
    TYPE_SFIXED32(15),
    /**
     * <pre>
     * Field type sfixed64.
     * </pre>
     *
     * <code>TYPE_SFIXED64 = 16;</code>
     */
    TYPE_SFIXED64(16),
    /**
     * <pre>
     * Field type sint32.
     * </pre>
     *
     * <code>TYPE_SINT32 = 17;</code>
     */
    TYPE_SINT32(17),
    /**
     * <pre>
     * Field type sint64.
     * </pre>
     *
     * <code>TYPE_SINT64 = 18;</code>
     */
    TYPE_SINT64(18),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * Field type unknown.
     * </pre>
     *
     * <code>TYPE_UNKNOWN = 0;</code>
     */
    public static final int TYPE_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * Field type double.
     * </pre>
     *
     * <code>TYPE_DOUBLE = 1;</code>
     */
    public static final int TYPE_DOUBLE_VALUE = 1;
    /**
     * <pre>
     * Field type float.
     * </pre>
     *
     * <code>TYPE_FLOAT = 2;</code>
     */
    public static final int TYPE_FLOAT_VALUE = 2;
    /**
     * <pre>
     * Field type int64.
     * </pre>
     *
     * <code>TYPE_INT64 = 3;</code>
     */
    public static final int TYPE_INT64_VALUE = 3;
    /**
     * <pre>
     * Field type uint64.
     * </pre>
     *
     * <code>TYPE_UINT64 = 4;</code>
     */
    public static final int TYPE_UINT64_VALUE = 4;
    /**
     * <pre>
     * Field type int32.
     * </pre>
     *
     * <code>TYPE_INT32 = 5;</code>
     */
    public static final int TYPE_INT32_VALUE = 5;
    /**
     * <pre>
     * Field type fixed64.
     * </pre>
     *
     * <code>TYPE_FIXED64 = 6;</code>
     */
    public static final int TYPE_FIXED64_VALUE = 6;
    /**
     * <pre>
     * Field type fixed32.
     * </pre>
     *
     * <code>TYPE_FIXED32 = 7;</code>
     */
    public static final int TYPE_FIXED32_VALUE = 7;
    /**
     * <pre>
     * Field type bool.
     * </pre>
     *
     * <code>TYPE_BOOL = 8;</code>
     */
    public static final int TYPE_BOOL_VALUE = 8;
    /**
     * <pre>
     * Field type string.
     * </pre>
     *
     * <code>TYPE_STRING = 9;</code>
     */
    public static final int TYPE_STRING_VALUE = 9;
    /**
     * <pre>
     * Field type group. Proto2 syntax only, and deprecated.
     * </pre>
     *
     * <code>TYPE_GROUP = 10;</code>
     */
    public static final int TYPE_GROUP_VALUE = 10;
    /**
     * <pre>
     * Field type message.
     * </pre>
     *
     * <code>TYPE_MESSAGE = 11;</code>
     */
    public static final int TYPE_MESSAGE_VALUE = 11;
    /**
     * <pre>
     * Field type bytes.
     * </pre>
     *
     * <code>TYPE_BYTES = 12;</code>
     */
    public static final int TYPE_BYTES_VALUE = 12;
    /**
     * <pre>
     * Field type uint32.
     * </pre>
     *
     * <code>TYPE_UINT32 = 13;</code>
     */
    public static final int TYPE_UINT32_VALUE = 13;
    /**
     * <pre>
     * Field type enum.
     * </pre>
     *
     * <code>TYPE_ENUM = 14;</code>
     */
    public static final int TYPE_ENUM_VALUE = 14;
    /**
     * <pre>
     * Field type sfixed32.
     * </pre>
     *
     * <code>TYPE_SFIXED32 = 15;</code>
     */
    public static final int TYPE_SFIXED32_VALUE = 15;
    /**
     * <pre>
     * Field type sfixed64.
     * </pre>
     *
     * <code>TYPE_SFIXED64 = 16;</code>
     */
    public static final int TYPE_SFIXED64_VALUE = 16;
    /**
     * <pre>
     * Field type sint32.
     * </pre>
     *
     * <code>TYPE_SINT32 = 17;</code>
     */
    public static final int TYPE_SINT32_VALUE = 17;
    /**
     * <pre>
     * Field type sint64.
     * </pre>
     *
     * <code>TYPE_SINT64 = 18;</code>
     */
    public static final int TYPE_SINT64_VALUE = 18;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Kind valueOf(int value) {
      return forNumber(value);
    }

    public static Kind forNumber(int value) {
      switch (value) {
        case 0: return TYPE_UNKNOWN;
        case 1: return TYPE_DOUBLE;
        case 2: return TYPE_FLOAT;
        case 3: return TYPE_INT64;
        case 4: return TYPE_UINT64;
        case 5: return TYPE_INT32;
        case 6: return TYPE_FIXED64;
        case 7: return TYPE_FIXED32;
        case 8: return TYPE_BOOL;
        case 9: return TYPE_STRING;
        case 10: return TYPE_GROUP;
        case 11: return TYPE_MESSAGE;
        case 12: return TYPE_BYTES;
        case 13: return TYPE_UINT32;
        case 14: return TYPE_ENUM;
        case 15: return TYPE_SFIXED32;
        case 16: return TYPE_SFIXED64;
        case 17: return TYPE_SINT32;
        case 18: return TYPE_SINT64;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Kind>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Kind> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Kind>() {
            public Kind findValueByNumber(int number) {
              return Kind.forNumber(number);
            }
          };

    private final int value;

    private Kind(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:google.protobuf.Field.Kind)
  }

  /**
   * <pre>
   * Whether a field is optional, required, or repeated.
   * </pre>
   *
   * Protobuf enum {@code google.protobuf.Field.Cardinality}
   */
  public enum Cardinality
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <pre>
     * For fields with unknown cardinality.
     * </pre>
     *
     * <code>CARDINALITY_UNKNOWN = 0;</code>
     */
    CARDINALITY_UNKNOWN(0),
    /**
     * <pre>
     * For optional fields.
     * </pre>
     *
     * <code>CARDINALITY_OPTIONAL = 1;</code>
     */
    CARDINALITY_OPTIONAL(1),
    /**
     * <pre>
     * For required fields. Proto2 syntax only.
     * </pre>
     *
     * <code>CARDINALITY_REQUIRED = 2;</code>
     */
    CARDINALITY_REQUIRED(2),
    /**
     * <pre>
     * For repeated fields.
     * </pre>
     *
     * <code>CARDINALITY_REPEATED = 3;</code>
     */
    CARDINALITY_REPEATED(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * For fields with unknown cardinality.
     * </pre>
     *
     * <code>CARDINALITY_UNKNOWN = 0;</code>
     */
    public static final int CARDINALITY_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * For optional fields.
     * </pre>
     *
     * <code>CARDINALITY_OPTIONAL = 1;</code>
     */
    public static final int CARDINALITY_OPTIONAL_VALUE = 1;
    /**
     * <pre>
     * For required fields. Proto2 syntax only.
     * </pre>
     *
     * <code>CARDINALITY_REQUIRED = 2;</code>
     */
    public static final int CARDINALITY_REQUIRED_VALUE = 2;
    /**
     * <pre>
     * For repeated fields.
     * </pre>
     *
     * <code>CARDINALITY_REPEATED = 3;</code>
     */
    public static final int CARDINALITY_REPEATED_VALUE = 3;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Cardinality valueOf(int value) {
      return forNumber(value);
    }

    public static Cardinality forNumber(int value) {
      switch (value) {
        case 0: return CARDINALITY_UNKNOWN;
        case 1: return CARDINALITY_OPTIONAL;
        case 2: return CARDINALITY_REQUIRED;
        case 3: return CARDINALITY_REPEATED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Cardinality>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Cardinality> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Cardinality>() {
            public Cardinality findValueByNumber(int number) {
              return Cardinality.forNumber(number);
            }
          };

    private final int value;

    private Cardinality(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:google.protobuf.Field.Cardinality)
  }

  private int bitField0_;
  public static final int KIND_FIELD_NUMBER = 1;
  private int kind_;
  /**
   * <pre>
   * The field type.
   * </pre>
   *
   * <code>optional .google.protobuf.Field.Kind kind = 1;</code>
   */
  public int getKindValue() {
    return kind_;
  }
  /**
   * <pre>
   * The field type.
   * </pre>
   *
   * <code>optional .google.protobuf.Field.Kind kind = 1;</code>
   */
  public com.google.protobuf.Field.Kind getKind() {
    com.google.protobuf.Field.Kind result = com.google.protobuf.Field.Kind.forNumber(kind_);
    return result == null ? com.google.protobuf.Field.Kind.UNRECOGNIZED : result;
  }
  /**
   * <pre>
   * The field type.
   * </pre>
   *
   * <code>optional .google.protobuf.Field.Kind kind = 1;</code>
   */
  private void setKindValue(int value) {
      kind_ = value;
  }
  /**
   * <pre>
   * The field type.
   * </pre>
   *
   * <code>optional .google.protobuf.Field.Kind kind = 1;</code>
   */
  private void setKind(com.google.protobuf.Field.Kind value) {
    if (value == null) {
      throw new NullPointerException();
    }
    
    kind_ = value.getNumber();
  }
  /**
   * <pre>
   * The field type.
   * </pre>
   *
   * <code>optional .google.protobuf.Field.Kind kind = 1;</code>
   */
  private void clearKind() {
    
    kind_ = 0;
  }

  public static final int CARDINALITY_FIELD_NUMBER = 2;
  private int cardinality_;
  /**
   * <pre>
   * The field cardinality.
   * </pre>
   *
   * <code>optional .google.protobuf.Field.Cardinality cardinality = 2;</code>
   */
  public int getCardinalityValue() {
    return cardinality_;
  }
  /**
   * <pre>
   * The field cardinality.
   * </pre>
   *
   * <code>optional .google.protobuf.Field.Cardinality cardinality = 2;</code>
   */
  public com.google.protobuf.Field.Cardinality getCardinality() {
    com.google.protobuf.Field.Cardinality result = com.google.protobuf.Field.Cardinality.forNumber(cardinality_);
    return result == null ? com.google.protobuf.Field.Cardinality.UNRECOGNIZED : result;
  }
  /**
   * <pre>
   * The field cardinality.
   * </pre>
   *
   * <code>optional .google.protobuf.Field.Cardinality cardinality = 2;</code>
   */
  private void setCardinalityValue(int value) {
      cardinality_ = value;
  }
  /**
   * <pre>
   * The field cardinality.
   * </pre>
   *
   * <code>optional .google.protobuf.Field.Cardinality cardinality = 2;</code>
   */
  private void setCardinality(com.google.protobuf.Field.Cardinality value) {
    if (value == null) {
      throw new NullPointerException();
    }
    
    cardinality_ = value.getNumber();
  }
  /**
   * <pre>
   * The field cardinality.
   * </pre>
   *
   * <code>optional .google.protobuf.Field.Cardinality cardinality = 2;</code>
   */
  private void clearCardinality() {
    
    cardinality_ = 0;
  }

  public static final int NUMBER_FIELD_NUMBER = 3;
  private int number_;
  /**
   * <pre>
   * The field number.
   * </pre>
   *
   * <code>optional int32 number = 3;</code>
   */
  public int getNumber() {
    return number_;
  }
  /**
   * <pre>
   * The field number.
   * </pre>
   *
   * <code>optional int32 number = 3;</code>
   */
  private void setNumber(int value) {
    
    number_ = value;
  }
  /**
   * <pre>
   * The field number.
   * </pre>
   *
   * <code>optional int32 number = 3;</code>
   */
  private void clearNumber() {
    
    number_ = 0;
  }

  public static final int NAME_FIELD_NUMBER = 4;
  private java.lang.String name_;
  /**
   * <pre>
   * The field name.
   * </pre>
   *
   * <code>optional string name = 4;</code>
   */
  public java.lang.String getName() {
    return name_;
  }
  /**
   * <pre>
   * The field name.
   * </pre>
   *
   * <code>optional string name = 4;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(name_);
  }
  /**
   * <pre>
   * The field name.
   * </pre>
   *
   * <code>optional string name = 4;</code>
   */
  private void setName(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    name_ = value;
  }
  /**
   * <pre>
   * The field name.
   * </pre>
   *
   * <code>optional string name = 4;</code>
   */
  private void clearName() {
    
    name_ = getDefaultInstance().getName();
  }
  /**
   * <pre>
   * The field name.
   * </pre>
   *
   * <code>optional string name = 4;</code>
   */
  private void setNameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    name_ = value.toStringUtf8();
  }

  public static final int TYPE_URL_FIELD_NUMBER = 6;
  private java.lang.String typeUrl_;
  /**
   * <pre>
   * The field type URL, without the scheme, for message or enumeration
   * types. Example: `"type.googleapis.com/google.protobuf.Timestamp"`.
   * </pre>
   *
   * <code>optional string type_url = 6;</code>
   */
  public java.lang.String getTypeUrl() {
    return typeUrl_;
  }
  /**
   * <pre>
   * The field type URL, without the scheme, for message or enumeration
   * types. Example: `"type.googleapis.com/google.protobuf.Timestamp"`.
   * </pre>
   *
   * <code>optional string type_url = 6;</code>
   */
  public com.google.protobuf.ByteString
      getTypeUrlBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(typeUrl_);
  }
  /**
   * <pre>
   * The field type URL, without the scheme, for message or enumeration
   * types. Example: `"type.googleapis.com/google.protobuf.Timestamp"`.
   * </pre>
   *
   * <code>optional string type_url = 6;</code>
   */
  private void setTypeUrl(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    typeUrl_ = value;
  }
  /**
   * <pre>
   * The field type URL, without the scheme, for message or enumeration
   * types. Example: `"type.googleapis.com/google.protobuf.Timestamp"`.
   * </pre>
   *
   * <code>optional string type_url = 6;</code>
   */
  private void clearTypeUrl() {
    
    typeUrl_ = getDefaultInstance().getTypeUrl();
  }
  /**
   * <pre>
   * The field type URL, without the scheme, for message or enumeration
   * types. Example: `"type.googleapis.com/google.protobuf.Timestamp"`.
   * </pre>
   *
   * <code>optional string type_url = 6;</code>
   */
  private void setTypeUrlBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    typeUrl_ = value.toStringUtf8();
  }

  public static final int ONEOF_INDEX_FIELD_NUMBER = 7;
  private int oneofIndex_;
  /**
   * <pre>
   * The index of the field type in `Type.oneofs`, for message or enumeration
   * types. The first type has index 1; zero means the type is not in the list.
   * </pre>
   *
   * <code>optional int32 oneof_index = 7;</code>
   */
  public int getOneofIndex() {
    return oneofIndex_;
  }
  /**
   * <pre>
   * The index of the field type in `Type.oneofs`, for message or enumeration
   * types. The first type has index 1; zero means the type is not in the list.
   * </pre>
   *
   * <code>optional int32 oneof_index = 7;</code>
   */
  private void setOneofIndex(int value) {
    
    oneofIndex_ = value;
  }
  /**
   * <pre>
   * The index of the field type in `Type.oneofs`, for message or enumeration
   * types. The first type has index 1; zero means the type is not in the list.
   * </pre>
   *
   * <code>optional int32 oneof_index = 7;</code>
   */
  private void clearOneofIndex() {
    
    oneofIndex_ = 0;
  }

  public static final int PACKED_FIELD_NUMBER = 8;
  private boolean packed_;
  /**
   * <pre>
   * Whether to use alternative packed wire representation.
   * </pre>
   *
   * <code>optional bool packed = 8;</code>
   */
  public boolean getPacked() {
    return packed_;
  }
  /**
   * <pre>
   * Whether to use alternative packed wire representation.
   * </pre>
   *
   * <code>optional bool packed = 8;</code>
   */
  private void setPacked(boolean value) {
    
    packed_ = value;
  }
  /**
   * <pre>
   * Whether to use alternative packed wire representation.
   * </pre>
   *
   * <code>optional bool packed = 8;</code>
   */
  private void clearPacked() {
    
    packed_ = false;
  }

  public static final int OPTIONS_FIELD_NUMBER = 9;
  private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.Option> options_;
  /**
   * <pre>
   * The protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 9;</code>
   */
  public java.util.List<com.google.protobuf.Option> getOptionsList() {
    return options_;
  }
  /**
   * <pre>
   * The protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 9;</code>
   */
  public java.util.List<? extends com.google.protobuf.OptionOrBuilder> 
      getOptionsOrBuilderList() {
    return options_;
  }
  /**
   * <pre>
   * The protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 9;</code>
   */
  public int getOptionsCount() {
    return options_.size();
  }
  /**
   * <pre>
   * The protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 9;</code>
   */
  public com.google.protobuf.Option getOptions(int index) {
    return options_.get(index);
  }
  /**
   * <pre>
   * The protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 9;</code>
   */
  public com.google.protobuf.OptionOrBuilder getOptionsOrBuilder(
      int index) {
    return options_.get(index);
  }
  private void ensureOptionsIsMutable() {
    if (!options_.isModifiable()) {
      options_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(options_);
     }
  }

  /**
   * <pre>
   * The protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 9;</code>
   */
  private void setOptions(
      int index, com.google.protobuf.Option value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureOptionsIsMutable();
    options_.set(index, value);
  }
  /**
   * <pre>
   * The protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 9;</code>
   */
  private void setOptions(
      int index, com.google.protobuf.Option.Builder builderForValue) {
    ensureOptionsIsMutable();
    options_.set(index, builderForValue.build());
  }
  /**
   * <pre>
   * The protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 9;</code>
   */
  private void addOptions(com.google.protobuf.Option value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureOptionsIsMutable();
    options_.add(value);
  }
  /**
   * <pre>
   * The protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 9;</code>
   */
  private void addOptions(
      int index, com.google.protobuf.Option value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureOptionsIsMutable();
    options_.add(index, value);
  }
  /**
   * <pre>
   * The protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 9;</code>
   */
  private void addOptions(
      com.google.protobuf.Option.Builder builderForValue) {
    ensureOptionsIsMutable();
    options_.add(builderForValue.build());
  }
  /**
   * <pre>
   * The protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 9;</code>
   */
  private void addOptions(
      int index, com.google.protobuf.Option.Builder builderForValue) {
    ensureOptionsIsMutable();
    options_.add(index, builderForValue.build());
  }
  /**
   * <pre>
   * The protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 9;</code>
   */
  private void addAllOptions(
      java.lang.Iterable<? extends com.google.protobuf.Option> values) {
    ensureOptionsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, options_);
  }
  /**
   * <pre>
   * The protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 9;</code>
   */
  private void clearOptions() {
    options_ = emptyProtobufList();
  }
  /**
   * <pre>
   * The protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 9;</code>
   */
  private void removeOptions(int index) {
    ensureOptionsIsMutable();
    options_.remove(index);
  }

  public static final int JSON_NAME_FIELD_NUMBER = 10;
  private java.lang.String jsonName_;
  /**
   * <pre>
   * The field JSON name.
   * </pre>
   *
   * <code>optional string json_name = 10;</code>
   */
  public java.lang.String getJsonName() {
    return jsonName_;
  }
  /**
   * <pre>
   * The field JSON name.
   * </pre>
   *
   * <code>optional string json_name = 10;</code>
   */
  public com.google.protobuf.ByteString
      getJsonNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(jsonName_);
  }
  /**
   * <pre>
   * The field JSON name.
   * </pre>
   *
   * <code>optional string json_name = 10;</code>
   */
  private void setJsonName(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    jsonName_ = value;
  }
  /**
   * <pre>
   * The field JSON name.
   * </pre>
   *
   * <code>optional string json_name = 10;</code>
   */
  private void clearJsonName() {
    
    jsonName_ = getDefaultInstance().getJsonName();
  }
  /**
   * <pre>
   * The field JSON name.
   * </pre>
   *
   * <code>optional string json_name = 10;</code>
   */
  private void setJsonNameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    jsonName_ = value.toStringUtf8();
  }

  public static final int DEFAULT_VALUE_FIELD_NUMBER = 11;
  private java.lang.String defaultValue_;
  /**
   * <pre>
   * The string value of the default value of this field. Proto2 syntax only.
   * </pre>
   *
   * <code>optional string default_value = 11;</code>
   */
  public java.lang.String getDefaultValue() {
    return defaultValue_;
  }
  /**
   * <pre>
   * The string value of the default value of this field. Proto2 syntax only.
   * </pre>
   *
   * <code>optional string default_value = 11;</code>
   */
  public com.google.protobuf.ByteString
      getDefaultValueBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(defaultValue_);
  }
  /**
   * <pre>
   * The string value of the default value of this field. Proto2 syntax only.
   * </pre>
   *
   * <code>optional string default_value = 11;</code>
   */
  private void setDefaultValue(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    defaultValue_ = value;
  }
  /**
   * <pre>
   * The string value of the default value of this field. Proto2 syntax only.
   * </pre>
   *
   * <code>optional string default_value = 11;</code>
   */
  private void clearDefaultValue() {
    
    defaultValue_ = getDefaultInstance().getDefaultValue();
  }
  /**
   * <pre>
   * The string value of the default value of this field. Proto2 syntax only.
   * </pre>
   *
   * <code>optional string default_value = 11;</code>
   */
  private void setDefaultValueBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    defaultValue_ = value.toStringUtf8();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (kind_ != com.google.protobuf.Field.Kind.TYPE_UNKNOWN.getNumber()) {
      output.writeEnum(1, kind_);
    }
    if (cardinality_ != com.google.protobuf.Field.Cardinality.CARDINALITY_UNKNOWN.getNumber()) {
      output.writeEnum(2, cardinality_);
    }
    if (number_ != 0) {
      output.writeInt32(3, number_);
    }
    if (!name_.isEmpty()) {
      output.writeString(4, getName());
    }
    if (!typeUrl_.isEmpty()) {
      output.writeString(6, getTypeUrl());
    }
    if (oneofIndex_ != 0) {
      output.writeInt32(7, oneofIndex_);
    }
    if (packed_ != false) {
      output.writeBool(8, packed_);
    }
    for (int i = 0; i < options_.size(); i++) {
      output.writeMessage(9, options_.get(i));
    }
    if (!jsonName_.isEmpty()) {
      output.writeString(10, getJsonName());
    }
    if (!defaultValue_.isEmpty()) {
      output.writeString(11, getDefaultValue());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (kind_ != com.google.protobuf.Field.Kind.TYPE_UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, kind_);
    }
    if (cardinality_ != com.google.protobuf.Field.Cardinality.CARDINALITY_UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, cardinality_);
    }
    if (number_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, number_);
    }
    if (!name_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(4, getName());
    }
    if (!typeUrl_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(6, getTypeUrl());
    }
    if (oneofIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, oneofIndex_);
    }
    if (packed_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, packed_);
    }
    for (int i = 0; i < options_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, options_.get(i));
    }
    if (!jsonName_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(10, getJsonName());
    }
    if (!defaultValue_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(11, getDefaultValue());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static com.google.protobuf.Field parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.protobuf.Field parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.protobuf.Field parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.protobuf.Field parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.protobuf.Field parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.protobuf.Field parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.protobuf.Field parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.google.protobuf.Field parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.protobuf.Field parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.protobuf.Field parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.protobuf.Field prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * <pre>
   * A single field of a message type.
   * </pre>
   *
   * Protobuf type {@code google.protobuf.Field}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.google.protobuf.Field, Builder> implements
      // @@protoc_insertion_point(builder_implements:google.protobuf.Field)
      com.google.protobuf.FieldOrBuilder {
    // Construct using com.google.protobuf.Field.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * The field type.
     * </pre>
     *
     * <code>optional .google.protobuf.Field.Kind kind = 1;</code>
     */
    public int getKindValue() {
      return instance.getKindValue();
    }
    /**
     * <pre>
     * The field type.
     * </pre>
     *
     * <code>optional .google.protobuf.Field.Kind kind = 1;</code>
     */
    public Builder setKindValue(int value) {
      copyOnWrite();
      instance.setKindValue(value);
      return this;
    }
    /**
     * <pre>
     * The field type.
     * </pre>
     *
     * <code>optional .google.protobuf.Field.Kind kind = 1;</code>
     */
    public com.google.protobuf.Field.Kind getKind() {
      return instance.getKind();
    }
    /**
     * <pre>
     * The field type.
     * </pre>
     *
     * <code>optional .google.protobuf.Field.Kind kind = 1;</code>
     */
    public Builder setKind(com.google.protobuf.Field.Kind value) {
      copyOnWrite();
      instance.setKind(value);
      return this;
    }
    /**
     * <pre>
     * The field type.
     * </pre>
     *
     * <code>optional .google.protobuf.Field.Kind kind = 1;</code>
     */
    public Builder clearKind() {
      copyOnWrite();
      instance.clearKind();
      return this;
    }

    /**
     * <pre>
     * The field cardinality.
     * </pre>
     *
     * <code>optional .google.protobuf.Field.Cardinality cardinality = 2;</code>
     */
    public int getCardinalityValue() {
      return instance.getCardinalityValue();
    }
    /**
     * <pre>
     * The field cardinality.
     * </pre>
     *
     * <code>optional .google.protobuf.Field.Cardinality cardinality = 2;</code>
     */
    public Builder setCardinalityValue(int value) {
      copyOnWrite();
      instance.setCardinalityValue(value);
      return this;
    }
    /**
     * <pre>
     * The field cardinality.
     * </pre>
     *
     * <code>optional .google.protobuf.Field.Cardinality cardinality = 2;</code>
     */
    public com.google.protobuf.Field.Cardinality getCardinality() {
      return instance.getCardinality();
    }
    /**
     * <pre>
     * The field cardinality.
     * </pre>
     *
     * <code>optional .google.protobuf.Field.Cardinality cardinality = 2;</code>
     */
    public Builder setCardinality(com.google.protobuf.Field.Cardinality value) {
      copyOnWrite();
      instance.setCardinality(value);
      return this;
    }
    /**
     * <pre>
     * The field cardinality.
     * </pre>
     *
     * <code>optional .google.protobuf.Field.Cardinality cardinality = 2;</code>
     */
    public Builder clearCardinality() {
      copyOnWrite();
      instance.clearCardinality();
      return this;
    }

    /**
     * <pre>
     * The field number.
     * </pre>
     *
     * <code>optional int32 number = 3;</code>
     */
    public int getNumber() {
      return instance.getNumber();
    }
    /**
     * <pre>
     * The field number.
     * </pre>
     *
     * <code>optional int32 number = 3;</code>
     */
    public Builder setNumber(int value) {
      copyOnWrite();
      instance.setNumber(value);
      return this;
    }
    /**
     * <pre>
     * The field number.
     * </pre>
     *
     * <code>optional int32 number = 3;</code>
     */
    public Builder clearNumber() {
      copyOnWrite();
      instance.clearNumber();
      return this;
    }

    /**
     * <pre>
     * The field name.
     * </pre>
     *
     * <code>optional string name = 4;</code>
     */
    public java.lang.String getName() {
      return instance.getName();
    }
    /**
     * <pre>
     * The field name.
     * </pre>
     *
     * <code>optional string name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      return instance.getNameBytes();
    }
    /**
     * <pre>
     * The field name.
     * </pre>
     *
     * <code>optional string name = 4;</code>
     */
    public Builder setName(
        java.lang.String value) {
      copyOnWrite();
      instance.setName(value);
      return this;
    }
    /**
     * <pre>
     * The field name.
     * </pre>
     *
     * <code>optional string name = 4;</code>
     */
    public Builder clearName() {
      copyOnWrite();
      instance.clearName();
      return this;
    }
    /**
     * <pre>
     * The field name.
     * </pre>
     *
     * <code>optional string name = 4;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameBytes(value);
      return this;
    }

    /**
     * <pre>
     * The field type URL, without the scheme, for message or enumeration
     * types. Example: `"type.googleapis.com/google.protobuf.Timestamp"`.
     * </pre>
     *
     * <code>optional string type_url = 6;</code>
     */
    public java.lang.String getTypeUrl() {
      return instance.getTypeUrl();
    }
    /**
     * <pre>
     * The field type URL, without the scheme, for message or enumeration
     * types. Example: `"type.googleapis.com/google.protobuf.Timestamp"`.
     * </pre>
     *
     * <code>optional string type_url = 6;</code>
     */
    public com.google.protobuf.ByteString
        getTypeUrlBytes() {
      return instance.getTypeUrlBytes();
    }
    /**
     * <pre>
     * The field type URL, without the scheme, for message or enumeration
     * types. Example: `"type.googleapis.com/google.protobuf.Timestamp"`.
     * </pre>
     *
     * <code>optional string type_url = 6;</code>
     */
    public Builder setTypeUrl(
        java.lang.String value) {
      copyOnWrite();
      instance.setTypeUrl(value);
      return this;
    }
    /**
     * <pre>
     * The field type URL, without the scheme, for message or enumeration
     * types. Example: `"type.googleapis.com/google.protobuf.Timestamp"`.
     * </pre>
     *
     * <code>optional string type_url = 6;</code>
     */
    public Builder clearTypeUrl() {
      copyOnWrite();
      instance.clearTypeUrl();
      return this;
    }
    /**
     * <pre>
     * The field type URL, without the scheme, for message or enumeration
     * types. Example: `"type.googleapis.com/google.protobuf.Timestamp"`.
     * </pre>
     *
     * <code>optional string type_url = 6;</code>
     */
    public Builder setTypeUrlBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTypeUrlBytes(value);
      return this;
    }

    /**
     * <pre>
     * The index of the field type in `Type.oneofs`, for message or enumeration
     * types. The first type has index 1; zero means the type is not in the list.
     * </pre>
     *
     * <code>optional int32 oneof_index = 7;</code>
     */
    public int getOneofIndex() {
      return instance.getOneofIndex();
    }
    /**
     * <pre>
     * The index of the field type in `Type.oneofs`, for message or enumeration
     * types. The first type has index 1; zero means the type is not in the list.
     * </pre>
     *
     * <code>optional int32 oneof_index = 7;</code>
     */
    public Builder setOneofIndex(int value) {
      copyOnWrite();
      instance.setOneofIndex(value);
      return this;
    }
    /**
     * <pre>
     * The index of the field type in `Type.oneofs`, for message or enumeration
     * types. The first type has index 1; zero means the type is not in the list.
     * </pre>
     *
     * <code>optional int32 oneof_index = 7;</code>
     */
    public Builder clearOneofIndex() {
      copyOnWrite();
      instance.clearOneofIndex();
      return this;
    }

    /**
     * <pre>
     * Whether to use alternative packed wire representation.
     * </pre>
     *
     * <code>optional bool packed = 8;</code>
     */
    public boolean getPacked() {
      return instance.getPacked();
    }
    /**
     * <pre>
     * Whether to use alternative packed wire representation.
     * </pre>
     *
     * <code>optional bool packed = 8;</code>
     */
    public Builder setPacked(boolean value) {
      copyOnWrite();
      instance.setPacked(value);
      return this;
    }
    /**
     * <pre>
     * Whether to use alternative packed wire representation.
     * </pre>
     *
     * <code>optional bool packed = 8;</code>
     */
    public Builder clearPacked() {
      copyOnWrite();
      instance.clearPacked();
      return this;
    }

    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 9;</code>
     */
    public java.util.List<com.google.protobuf.Option> getOptionsList() {
      return java.util.Collections.unmodifiableList(
          instance.getOptionsList());
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 9;</code>
     */
    public int getOptionsCount() {
      return instance.getOptionsCount();
    }/**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 9;</code>
     */
    public com.google.protobuf.Option getOptions(int index) {
      return instance.getOptions(index);
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 9;</code>
     */
    public Builder setOptions(
        int index, com.google.protobuf.Option value) {
      copyOnWrite();
      instance.setOptions(index, value);
      return this;
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 9;</code>
     */
    public Builder setOptions(
        int index, com.google.protobuf.Option.Builder builderForValue) {
      copyOnWrite();
      instance.setOptions(index, builderForValue);
      return this;
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 9;</code>
     */
    public Builder addOptions(com.google.protobuf.Option value) {
      copyOnWrite();
      instance.addOptions(value);
      return this;
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 9;</code>
     */
    public Builder addOptions(
        int index, com.google.protobuf.Option value) {
      copyOnWrite();
      instance.addOptions(index, value);
      return this;
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 9;</code>
     */
    public Builder addOptions(
        com.google.protobuf.Option.Builder builderForValue) {
      copyOnWrite();
      instance.addOptions(builderForValue);
      return this;
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 9;</code>
     */
    public Builder addOptions(
        int index, com.google.protobuf.Option.Builder builderForValue) {
      copyOnWrite();
      instance.addOptions(index, builderForValue);
      return this;
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 9;</code>
     */
    public Builder addAllOptions(
        java.lang.Iterable<? extends com.google.protobuf.Option> values) {
      copyOnWrite();
      instance.addAllOptions(values);
      return this;
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 9;</code>
     */
    public Builder clearOptions() {
      copyOnWrite();
      instance.clearOptions();
      return this;
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 9;</code>
     */
    public Builder removeOptions(int index) {
      copyOnWrite();
      instance.removeOptions(index);
      return this;
    }

    /**
     * <pre>
     * The field JSON name.
     * </pre>
     *
     * <code>optional string json_name = 10;</code>
     */
    public java.lang.String getJsonName() {
      return instance.getJsonName();
    }
    /**
     * <pre>
     * The field JSON name.
     * </pre>
     *
     * <code>optional string json_name = 10;</code>
     */
    public com.google.protobuf.ByteString
        getJsonNameBytes() {
      return instance.getJsonNameBytes();
    }
    /**
     * <pre>
     * The field JSON name.
     * </pre>
     *
     * <code>optional string json_name = 10;</code>
     */
    public Builder setJsonName(
        java.lang.String value) {
      copyOnWrite();
      instance.setJsonName(value);
      return this;
    }
    /**
     * <pre>
     * The field JSON name.
     * </pre>
     *
     * <code>optional string json_name = 10;</code>
     */
    public Builder clearJsonName() {
      copyOnWrite();
      instance.clearJsonName();
      return this;
    }
    /**
     * <pre>
     * The field JSON name.
     * </pre>
     *
     * <code>optional string json_name = 10;</code>
     */
    public Builder setJsonNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setJsonNameBytes(value);
      return this;
    }

    /**
     * <pre>
     * The string value of the default value of this field. Proto2 syntax only.
     * </pre>
     *
     * <code>optional string default_value = 11;</code>
     */
    public java.lang.String getDefaultValue() {
      return instance.getDefaultValue();
    }
    /**
     * <pre>
     * The string value of the default value of this field. Proto2 syntax only.
     * </pre>
     *
     * <code>optional string default_value = 11;</code>
     */
    public com.google.protobuf.ByteString
        getDefaultValueBytes() {
      return instance.getDefaultValueBytes();
    }
    /**
     * <pre>
     * The string value of the default value of this field. Proto2 syntax only.
     * </pre>
     *
     * <code>optional string default_value = 11;</code>
     */
    public Builder setDefaultValue(
        java.lang.String value) {
      copyOnWrite();
      instance.setDefaultValue(value);
      return this;
    }
    /**
     * <pre>
     * The string value of the default value of this field. Proto2 syntax only.
     * </pre>
     *
     * <code>optional string default_value = 11;</code>
     */
    public Builder clearDefaultValue() {
      copyOnWrite();
      instance.clearDefaultValue();
      return this;
    }
    /**
     * <pre>
     * The string value of the default value of this field. Proto2 syntax only.
     * </pre>
     *
     * <code>optional string default_value = 11;</code>
     */
    public Builder setDefaultValueBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDefaultValueBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.protobuf.Field)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.google.protobuf.Field();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        options_.makeImmutable();
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        com.google.protobuf.Field other = (com.google.protobuf.Field) arg1;
        kind_ = visitor.visitInt(kind_ != 0, kind_,    other.kind_ != 0, other.kind_);
        cardinality_ = visitor.visitInt(cardinality_ != 0, cardinality_,    other.cardinality_ != 0, other.cardinality_);
        number_ = visitor.visitInt(number_ != 0, number_,
            other.number_ != 0, other.number_);
        name_ = visitor.visitString(!name_.isEmpty(), name_,
            !other.name_.isEmpty(), other.name_);
        typeUrl_ = visitor.visitString(!typeUrl_.isEmpty(), typeUrl_,
            !other.typeUrl_.isEmpty(), other.typeUrl_);
        oneofIndex_ = visitor.visitInt(oneofIndex_ != 0, oneofIndex_,
            other.oneofIndex_ != 0, other.oneofIndex_);
        packed_ = visitor.visitBoolean(packed_ != false, packed_,
            other.packed_ != false, other.packed_);
        options_= visitor.visitList(options_, other.options_);
        jsonName_ = visitor.visitString(!jsonName_.isEmpty(), jsonName_,
            !other.jsonName_.isEmpty(), other.jsonName_);
        defaultValue_ = visitor.visitString(!defaultValue_.isEmpty(), defaultValue_,
            !other.defaultValue_.isEmpty(), other.defaultValue_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();

                kind_ = rawValue;
                break;
              }
              case 16: {
                int rawValue = input.readEnum();

                cardinality_ = rawValue;
                break;
              }
              case 24: {

                number_ = input.readInt32();
                break;
              }
              case 34: {
                String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
              case 50: {
                String s = input.readStringRequireUtf8();

                typeUrl_ = s;
                break;
              }
              case 56: {

                oneofIndex_ = input.readInt32();
                break;
              }
              case 64: {

                packed_ = input.readBool();
                break;
              }
              case 74: {
                if (!options_.isModifiable()) {
                  options_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(options_);
                }
                options_.add(
                    input.readMessage(com.google.protobuf.Option.parser(), extensionRegistry));
                break;
              }
              case 82: {
                String s = input.readStringRequireUtf8();

                jsonName_ = s;
                break;
              }
              case 90: {
                String s = input.readStringRequireUtf8();

                defaultValue_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (com.google.protobuf.Field.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:google.protobuf.Field)
  private static final com.google.protobuf.Field DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Field();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static com.google.protobuf.Field getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Field> PARSER;

  public static com.google.protobuf.Parser<Field> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

