// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/field_mask.proto

package com.google.protobuf;

public interface FieldMaskOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.FieldMask)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * The set of field mask paths.
   * </pre>
   *
   * <code>repeated string paths = 1;</code>
   */
  java.util.List<String>
      getPathsList();
  /**
   * <pre>
   * The set of field mask paths.
   * </pre>
   *
   * <code>repeated string paths = 1;</code>
   */
  int getPathsCount();
  /**
   * <pre>
   * The set of field mask paths.
   * </pre>
   *
   * <code>repeated string paths = 1;</code>
   */
  java.lang.String getPaths(int index);
  /**
   * <pre>
   * The set of field mask paths.
   * </pre>
   *
   * <code>repeated string paths = 1;</code>
   */
  com.google.protobuf.ByteString
      getPathsBytes(int index);
}
