// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/wrappers.proto

package com.google.protobuf;

public interface FloatValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.FloatValue)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * The float value.
   * </pre>
   *
   * <code>optional float value = 1;</code>
   */
  float getValue();
}
