// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/wrappers.proto

package com.google.protobuf;

public interface Int64ValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.Int64Value)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * The int64 value.
   * </pre>
   *
   * <code>optional int64 value = 1;</code>
   */
  long getValue();
}
