// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/source_context.proto

package com.google.protobuf;

/**
 * <pre>
 * `SourceContext` represents information about the source of a
 * protobuf element, like the file in which it is defined.
 * </pre>
 *
 * Protobuf type {@code google.protobuf.SourceContext}
 */
public  final class SourceContext extends
    com.google.protobuf.GeneratedMessageLite<
        SourceContext, SourceContext.Builder> implements
    // @@protoc_insertion_point(message_implements:google.protobuf.SourceContext)
    SourceContextOrBuilder {
  private SourceContext() {
    fileName_ = "";
  }
  public static final int FILE_NAME_FIELD_NUMBER = 1;
  private java.lang.String fileName_;
  /**
   * <pre>
   * The path-qualified name of the .proto file that contained the associated
   * protobuf element.  For example: `"google/protobuf/source_context.proto"`.
   * </pre>
   *
   * <code>optional string file_name = 1;</code>
   */
  public java.lang.String getFileName() {
    return fileName_;
  }
  /**
   * <pre>
   * The path-qualified name of the .proto file that contained the associated
   * protobuf element.  For example: `"google/protobuf/source_context.proto"`.
   * </pre>
   *
   * <code>optional string file_name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getFileNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(fileName_);
  }
  /**
   * <pre>
   * The path-qualified name of the .proto file that contained the associated
   * protobuf element.  For example: `"google/protobuf/source_context.proto"`.
   * </pre>
   *
   * <code>optional string file_name = 1;</code>
   */
  private void setFileName(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    fileName_ = value;
  }
  /**
   * <pre>
   * The path-qualified name of the .proto file that contained the associated
   * protobuf element.  For example: `"google/protobuf/source_context.proto"`.
   * </pre>
   *
   * <code>optional string file_name = 1;</code>
   */
  private void clearFileName() {
    
    fileName_ = getDefaultInstance().getFileName();
  }
  /**
   * <pre>
   * The path-qualified name of the .proto file that contained the associated
   * protobuf element.  For example: `"google/protobuf/source_context.proto"`.
   * </pre>
   *
   * <code>optional string file_name = 1;</code>
   */
  private void setFileNameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    fileName_ = value.toStringUtf8();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!fileName_.isEmpty()) {
      output.writeString(1, getFileName());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!fileName_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getFileName());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static com.google.protobuf.SourceContext parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.protobuf.SourceContext parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.protobuf.SourceContext parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.protobuf.SourceContext parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.protobuf.SourceContext parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.protobuf.SourceContext parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.protobuf.SourceContext parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.google.protobuf.SourceContext parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.protobuf.SourceContext parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.protobuf.SourceContext parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.protobuf.SourceContext prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * <pre>
   * `SourceContext` represents information about the source of a
   * protobuf element, like the file in which it is defined.
   * </pre>
   *
   * Protobuf type {@code google.protobuf.SourceContext}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.google.protobuf.SourceContext, Builder> implements
      // @@protoc_insertion_point(builder_implements:google.protobuf.SourceContext)
      com.google.protobuf.SourceContextOrBuilder {
    // Construct using com.google.protobuf.SourceContext.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * The path-qualified name of the .proto file that contained the associated
     * protobuf element.  For example: `"google/protobuf/source_context.proto"`.
     * </pre>
     *
     * <code>optional string file_name = 1;</code>
     */
    public java.lang.String getFileName() {
      return instance.getFileName();
    }
    /**
     * <pre>
     * The path-qualified name of the .proto file that contained the associated
     * protobuf element.  For example: `"google/protobuf/source_context.proto"`.
     * </pre>
     *
     * <code>optional string file_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      return instance.getFileNameBytes();
    }
    /**
     * <pre>
     * The path-qualified name of the .proto file that contained the associated
     * protobuf element.  For example: `"google/protobuf/source_context.proto"`.
     * </pre>
     *
     * <code>optional string file_name = 1;</code>
     */
    public Builder setFileName(
        java.lang.String value) {
      copyOnWrite();
      instance.setFileName(value);
      return this;
    }
    /**
     * <pre>
     * The path-qualified name of the .proto file that contained the associated
     * protobuf element.  For example: `"google/protobuf/source_context.proto"`.
     * </pre>
     *
     * <code>optional string file_name = 1;</code>
     */
    public Builder clearFileName() {
      copyOnWrite();
      instance.clearFileName();
      return this;
    }
    /**
     * <pre>
     * The path-qualified name of the .proto file that contained the associated
     * protobuf element.  For example: `"google/protobuf/source_context.proto"`.
     * </pre>
     *
     * <code>optional string file_name = 1;</code>
     */
    public Builder setFileNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setFileNameBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.protobuf.SourceContext)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.google.protobuf.SourceContext();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        com.google.protobuf.SourceContext other = (com.google.protobuf.SourceContext) arg1;
        fileName_ = visitor.visitString(!fileName_.isEmpty(), fileName_,
            !other.fileName_.isEmpty(), other.fileName_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                fileName_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (com.google.protobuf.SourceContext.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:google.protobuf.SourceContext)
  private static final com.google.protobuf.SourceContext DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new SourceContext();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static com.google.protobuf.SourceContext getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<SourceContext> PARSER;

  public static com.google.protobuf.Parser<SourceContext> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

