// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/type.proto

package com.google.protobuf;

/**
 * <pre>
 * The syntax in which a protocol buffer element is defined.
 * </pre>
 *
 * Protobuf enum {@code google.protobuf.Syntax}
 */
public enum Syntax
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <pre>
   * Syntax `proto2`.
   * </pre>
   *
   * <code>SYNTAX_PROTO2 = 0;</code>
   */
  SYNTAX_PROTO2(0),
  /**
   * <pre>
   * Syntax `proto3`.
   * </pre>
   *
   * <code>SYNTAX_PROTO3 = 1;</code>
   */
  SYNTAX_PROTO3(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * Syntax `proto2`.
   * </pre>
   *
   * <code>SYNTAX_PROTO2 = 0;</code>
   */
  public static final int SYNTAX_PROTO2_VALUE = 0;
  /**
   * <pre>
   * Syntax `proto3`.
   * </pre>
   *
   * <code>SYNTAX_PROTO3 = 1;</code>
   */
  public static final int SYNTAX_PROTO3_VALUE = 1;


  public final int getNumber() {
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Syntax valueOf(int value) {
    return forNumber(value);
  }

  public static Syntax forNumber(int value) {
    switch (value) {
      case 0: return SYNTAX_PROTO2;
      case 1: return SYNTAX_PROTO3;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Syntax>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Syntax> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Syntax>() {
          public Syntax findValueByNumber(int number) {
            return Syntax.forNumber(number);
          }
        };

  private final int value;

  private Syntax(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:google.protobuf.Syntax)
}

