// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/type.proto

package com.google.protobuf;

/**
 * <pre>
 * A protocol buffer message type.
 * </pre>
 *
 * Protobuf type {@code google.protobuf.Type}
 */
public  final class Type extends
    com.google.protobuf.GeneratedMessageLite<
        Type, Type.Builder> implements
    // @@protoc_insertion_point(message_implements:google.protobuf.Type)
    TypeOrBuilder {
  private Type() {
    name_ = "";
    fields_ = emptyProtobufList();
    oneofs_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    options_ = emptyProtobufList();
  }
  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  private java.lang.String name_;
  /**
   * <pre>
   * The fully qualified message name.
   * </pre>
   *
   * <code>optional string name = 1;</code>
   */
  public java.lang.String getName() {
    return name_;
  }
  /**
   * <pre>
   * The fully qualified message name.
   * </pre>
   *
   * <code>optional string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(name_);
  }
  /**
   * <pre>
   * The fully qualified message name.
   * </pre>
   *
   * <code>optional string name = 1;</code>
   */
  private void setName(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    name_ = value;
  }
  /**
   * <pre>
   * The fully qualified message name.
   * </pre>
   *
   * <code>optional string name = 1;</code>
   */
  private void clearName() {
    
    name_ = getDefaultInstance().getName();
  }
  /**
   * <pre>
   * The fully qualified message name.
   * </pre>
   *
   * <code>optional string name = 1;</code>
   */
  private void setNameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    name_ = value.toStringUtf8();
  }

  public static final int FIELDS_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.Field> fields_;
  /**
   * <pre>
   * The list of fields.
   * </pre>
   *
   * <code>repeated .google.protobuf.Field fields = 2;</code>
   */
  public java.util.List<com.google.protobuf.Field> getFieldsList() {
    return fields_;
  }
  /**
   * <pre>
   * The list of fields.
   * </pre>
   *
   * <code>repeated .google.protobuf.Field fields = 2;</code>
   */
  public java.util.List<? extends com.google.protobuf.FieldOrBuilder> 
      getFieldsOrBuilderList() {
    return fields_;
  }
  /**
   * <pre>
   * The list of fields.
   * </pre>
   *
   * <code>repeated .google.protobuf.Field fields = 2;</code>
   */
  public int getFieldsCount() {
    return fields_.size();
  }
  /**
   * <pre>
   * The list of fields.
   * </pre>
   *
   * <code>repeated .google.protobuf.Field fields = 2;</code>
   */
  public com.google.protobuf.Field getFields(int index) {
    return fields_.get(index);
  }
  /**
   * <pre>
   * The list of fields.
   * </pre>
   *
   * <code>repeated .google.protobuf.Field fields = 2;</code>
   */
  public com.google.protobuf.FieldOrBuilder getFieldsOrBuilder(
      int index) {
    return fields_.get(index);
  }
  private void ensureFieldsIsMutable() {
    if (!fields_.isModifiable()) {
      fields_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(fields_);
     }
  }

  /**
   * <pre>
   * The list of fields.
   * </pre>
   *
   * <code>repeated .google.protobuf.Field fields = 2;</code>
   */
  private void setFields(
      int index, com.google.protobuf.Field value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureFieldsIsMutable();
    fields_.set(index, value);
  }
  /**
   * <pre>
   * The list of fields.
   * </pre>
   *
   * <code>repeated .google.protobuf.Field fields = 2;</code>
   */
  private void setFields(
      int index, com.google.protobuf.Field.Builder builderForValue) {
    ensureFieldsIsMutable();
    fields_.set(index, builderForValue.build());
  }
  /**
   * <pre>
   * The list of fields.
   * </pre>
   *
   * <code>repeated .google.protobuf.Field fields = 2;</code>
   */
  private void addFields(com.google.protobuf.Field value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureFieldsIsMutable();
    fields_.add(value);
  }
  /**
   * <pre>
   * The list of fields.
   * </pre>
   *
   * <code>repeated .google.protobuf.Field fields = 2;</code>
   */
  private void addFields(
      int index, com.google.protobuf.Field value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureFieldsIsMutable();
    fields_.add(index, value);
  }
  /**
   * <pre>
   * The list of fields.
   * </pre>
   *
   * <code>repeated .google.protobuf.Field fields = 2;</code>
   */
  private void addFields(
      com.google.protobuf.Field.Builder builderForValue) {
    ensureFieldsIsMutable();
    fields_.add(builderForValue.build());
  }
  /**
   * <pre>
   * The list of fields.
   * </pre>
   *
   * <code>repeated .google.protobuf.Field fields = 2;</code>
   */
  private void addFields(
      int index, com.google.protobuf.Field.Builder builderForValue) {
    ensureFieldsIsMutable();
    fields_.add(index, builderForValue.build());
  }
  /**
   * <pre>
   * The list of fields.
   * </pre>
   *
   * <code>repeated .google.protobuf.Field fields = 2;</code>
   */
  private void addAllFields(
      java.lang.Iterable<? extends com.google.protobuf.Field> values) {
    ensureFieldsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, fields_);
  }
  /**
   * <pre>
   * The list of fields.
   * </pre>
   *
   * <code>repeated .google.protobuf.Field fields = 2;</code>
   */
  private void clearFields() {
    fields_ = emptyProtobufList();
  }
  /**
   * <pre>
   * The list of fields.
   * </pre>
   *
   * <code>repeated .google.protobuf.Field fields = 2;</code>
   */
  private void removeFields(int index) {
    ensureFieldsIsMutable();
    fields_.remove(index);
  }

  public static final int ONEOFS_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.ProtobufList<String> oneofs_;
  /**
   * <pre>
   * The list of types appearing in `oneof` definitions in this type.
   * </pre>
   *
   * <code>repeated string oneofs = 3;</code>
   */
  public java.util.List<String> getOneofsList() {
    return oneofs_;
  }
  /**
   * <pre>
   * The list of types appearing in `oneof` definitions in this type.
   * </pre>
   *
   * <code>repeated string oneofs = 3;</code>
   */
  public int getOneofsCount() {
    return oneofs_.size();
  }
  /**
   * <pre>
   * The list of types appearing in `oneof` definitions in this type.
   * </pre>
   *
   * <code>repeated string oneofs = 3;</code>
   */
  public java.lang.String getOneofs(int index) {
    return oneofs_.get(index);
  }
  /**
   * <pre>
   * The list of types appearing in `oneof` definitions in this type.
   * </pre>
   *
   * <code>repeated string oneofs = 3;</code>
   */
  public com.google.protobuf.ByteString
      getOneofsBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        oneofs_.get(index));
  }
  private void ensureOneofsIsMutable() {
    if (!oneofs_.isModifiable()) {
      oneofs_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(oneofs_);
     }
  }
  /**
   * <pre>
   * The list of types appearing in `oneof` definitions in this type.
   * </pre>
   *
   * <code>repeated string oneofs = 3;</code>
   */
  private void setOneofs(
      int index, java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  ensureOneofsIsMutable();
    oneofs_.set(index, value);
  }
  /**
   * <pre>
   * The list of types appearing in `oneof` definitions in this type.
   * </pre>
   *
   * <code>repeated string oneofs = 3;</code>
   */
  private void addOneofs(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  ensureOneofsIsMutable();
    oneofs_.add(value);
  }
  /**
   * <pre>
   * The list of types appearing in `oneof` definitions in this type.
   * </pre>
   *
   * <code>repeated string oneofs = 3;</code>
   */
  private void addAllOneofs(
      java.lang.Iterable<java.lang.String> values) {
    ensureOneofsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, oneofs_);
  }
  /**
   * <pre>
   * The list of types appearing in `oneof` definitions in this type.
   * </pre>
   *
   * <code>repeated string oneofs = 3;</code>
   */
  private void clearOneofs() {
    oneofs_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * <pre>
   * The list of types appearing in `oneof` definitions in this type.
   * </pre>
   *
   * <code>repeated string oneofs = 3;</code>
   */
  private void addOneofsBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    ensureOneofsIsMutable();
    oneofs_.add(value.toStringUtf8());
  }

  public static final int OPTIONS_FIELD_NUMBER = 4;
  private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.Option> options_;
  /**
   * <pre>
   * The protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 4;</code>
   */
  public java.util.List<com.google.protobuf.Option> getOptionsList() {
    return options_;
  }
  /**
   * <pre>
   * The protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 4;</code>
   */
  public java.util.List<? extends com.google.protobuf.OptionOrBuilder> 
      getOptionsOrBuilderList() {
    return options_;
  }
  /**
   * <pre>
   * The protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 4;</code>
   */
  public int getOptionsCount() {
    return options_.size();
  }
  /**
   * <pre>
   * The protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 4;</code>
   */
  public com.google.protobuf.Option getOptions(int index) {
    return options_.get(index);
  }
  /**
   * <pre>
   * The protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 4;</code>
   */
  public com.google.protobuf.OptionOrBuilder getOptionsOrBuilder(
      int index) {
    return options_.get(index);
  }
  private void ensureOptionsIsMutable() {
    if (!options_.isModifiable()) {
      options_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(options_);
     }
  }

  /**
   * <pre>
   * The protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 4;</code>
   */
  private void setOptions(
      int index, com.google.protobuf.Option value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureOptionsIsMutable();
    options_.set(index, value);
  }
  /**
   * <pre>
   * The protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 4;</code>
   */
  private void setOptions(
      int index, com.google.protobuf.Option.Builder builderForValue) {
    ensureOptionsIsMutable();
    options_.set(index, builderForValue.build());
  }
  /**
   * <pre>
   * The protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 4;</code>
   */
  private void addOptions(com.google.protobuf.Option value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureOptionsIsMutable();
    options_.add(value);
  }
  /**
   * <pre>
   * The protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 4;</code>
   */
  private void addOptions(
      int index, com.google.protobuf.Option value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureOptionsIsMutable();
    options_.add(index, value);
  }
  /**
   * <pre>
   * The protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 4;</code>
   */
  private void addOptions(
      com.google.protobuf.Option.Builder builderForValue) {
    ensureOptionsIsMutable();
    options_.add(builderForValue.build());
  }
  /**
   * <pre>
   * The protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 4;</code>
   */
  private void addOptions(
      int index, com.google.protobuf.Option.Builder builderForValue) {
    ensureOptionsIsMutable();
    options_.add(index, builderForValue.build());
  }
  /**
   * <pre>
   * The protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 4;</code>
   */
  private void addAllOptions(
      java.lang.Iterable<? extends com.google.protobuf.Option> values) {
    ensureOptionsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, options_);
  }
  /**
   * <pre>
   * The protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 4;</code>
   */
  private void clearOptions() {
    options_ = emptyProtobufList();
  }
  /**
   * <pre>
   * The protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 4;</code>
   */
  private void removeOptions(int index) {
    ensureOptionsIsMutable();
    options_.remove(index);
  }

  public static final int SOURCE_CONTEXT_FIELD_NUMBER = 5;
  private com.google.protobuf.SourceContext sourceContext_;
  /**
   * <pre>
   * The source context.
   * </pre>
   *
   * <code>optional .google.protobuf.SourceContext source_context = 5;</code>
   */
  public boolean hasSourceContext() {
    return sourceContext_ != null;
  }
  /**
   * <pre>
   * The source context.
   * </pre>
   *
   * <code>optional .google.protobuf.SourceContext source_context = 5;</code>
   */
  public com.google.protobuf.SourceContext getSourceContext() {
    return sourceContext_ == null ? com.google.protobuf.SourceContext.getDefaultInstance() : sourceContext_;
  }
  /**
   * <pre>
   * The source context.
   * </pre>
   *
   * <code>optional .google.protobuf.SourceContext source_context = 5;</code>
   */
  private void setSourceContext(com.google.protobuf.SourceContext value) {
    if (value == null) {
      throw new NullPointerException();
    }
    sourceContext_ = value;
    
    }
  /**
   * <pre>
   * The source context.
   * </pre>
   *
   * <code>optional .google.protobuf.SourceContext source_context = 5;</code>
   */
  private void setSourceContext(
      com.google.protobuf.SourceContext.Builder builderForValue) {
    sourceContext_ = builderForValue.build();
    
  }
  /**
   * <pre>
   * The source context.
   * </pre>
   *
   * <code>optional .google.protobuf.SourceContext source_context = 5;</code>
   */
  private void mergeSourceContext(com.google.protobuf.SourceContext value) {
    if (sourceContext_ != null &&
        sourceContext_ != com.google.protobuf.SourceContext.getDefaultInstance()) {
      sourceContext_ =
        com.google.protobuf.SourceContext.newBuilder(sourceContext_).mergeFrom(value).buildPartial();
    } else {
      sourceContext_ = value;
    }
    
  }
  /**
   * <pre>
   * The source context.
   * </pre>
   *
   * <code>optional .google.protobuf.SourceContext source_context = 5;</code>
   */
  private void clearSourceContext() {  sourceContext_ = null;
    
  }

  public static final int SYNTAX_FIELD_NUMBER = 6;
  private int syntax_;
  /**
   * <pre>
   * The source syntax.
   * </pre>
   *
   * <code>optional .google.protobuf.Syntax syntax = 6;</code>
   */
  public int getSyntaxValue() {
    return syntax_;
  }
  /**
   * <pre>
   * The source syntax.
   * </pre>
   *
   * <code>optional .google.protobuf.Syntax syntax = 6;</code>
   */
  public com.google.protobuf.Syntax getSyntax() {
    com.google.protobuf.Syntax result = com.google.protobuf.Syntax.forNumber(syntax_);
    return result == null ? com.google.protobuf.Syntax.UNRECOGNIZED : result;
  }
  /**
   * <pre>
   * The source syntax.
   * </pre>
   *
   * <code>optional .google.protobuf.Syntax syntax = 6;</code>
   */
  private void setSyntaxValue(int value) {
      syntax_ = value;
  }
  /**
   * <pre>
   * The source syntax.
   * </pre>
   *
   * <code>optional .google.protobuf.Syntax syntax = 6;</code>
   */
  private void setSyntax(com.google.protobuf.Syntax value) {
    if (value == null) {
      throw new NullPointerException();
    }
    
    syntax_ = value.getNumber();
  }
  /**
   * <pre>
   * The source syntax.
   * </pre>
   *
   * <code>optional .google.protobuf.Syntax syntax = 6;</code>
   */
  private void clearSyntax() {
    
    syntax_ = 0;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!name_.isEmpty()) {
      output.writeString(1, getName());
    }
    for (int i = 0; i < fields_.size(); i++) {
      output.writeMessage(2, fields_.get(i));
    }
    for (int i = 0; i < oneofs_.size(); i++) {
      output.writeString(3, oneofs_.get(i));
    }
    for (int i = 0; i < options_.size(); i++) {
      output.writeMessage(4, options_.get(i));
    }
    if (sourceContext_ != null) {
      output.writeMessage(5, getSourceContext());
    }
    if (syntax_ != com.google.protobuf.Syntax.SYNTAX_PROTO2.getNumber()) {
      output.writeEnum(6, syntax_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!name_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getName());
    }
    for (int i = 0; i < fields_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, fields_.get(i));
    }
    {
      int dataSize = 0;
      for (int i = 0; i < oneofs_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeStringSizeNoTag(oneofs_.get(i));
      }
      size += dataSize;
      size += 1 * getOneofsList().size();
    }
    for (int i = 0; i < options_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, options_.get(i));
    }
    if (sourceContext_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getSourceContext());
    }
    if (syntax_ != com.google.protobuf.Syntax.SYNTAX_PROTO2.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, syntax_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static com.google.protobuf.Type parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.protobuf.Type parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.protobuf.Type parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.google.protobuf.Type parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.google.protobuf.Type parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.protobuf.Type parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.protobuf.Type parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.google.protobuf.Type parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.google.protobuf.Type parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.google.protobuf.Type parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.protobuf.Type prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * <pre>
   * A protocol buffer message type.
   * </pre>
   *
   * Protobuf type {@code google.protobuf.Type}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.google.protobuf.Type, Builder> implements
      // @@protoc_insertion_point(builder_implements:google.protobuf.Type)
      com.google.protobuf.TypeOrBuilder {
    // Construct using com.google.protobuf.Type.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * The fully qualified message name.
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      return instance.getName();
    }
    /**
     * <pre>
     * The fully qualified message name.
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      return instance.getNameBytes();
    }
    /**
     * <pre>
     * The fully qualified message name.
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      copyOnWrite();
      instance.setName(value);
      return this;
    }
    /**
     * <pre>
     * The fully qualified message name.
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    public Builder clearName() {
      copyOnWrite();
      instance.clearName();
      return this;
    }
    /**
     * <pre>
     * The fully qualified message name.
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameBytes(value);
      return this;
    }

    /**
     * <pre>
     * The list of fields.
     * </pre>
     *
     * <code>repeated .google.protobuf.Field fields = 2;</code>
     */
    public java.util.List<com.google.protobuf.Field> getFieldsList() {
      return java.util.Collections.unmodifiableList(
          instance.getFieldsList());
    }
    /**
     * <pre>
     * The list of fields.
     * </pre>
     *
     * <code>repeated .google.protobuf.Field fields = 2;</code>
     */
    public int getFieldsCount() {
      return instance.getFieldsCount();
    }/**
     * <pre>
     * The list of fields.
     * </pre>
     *
     * <code>repeated .google.protobuf.Field fields = 2;</code>
     */
    public com.google.protobuf.Field getFields(int index) {
      return instance.getFields(index);
    }
    /**
     * <pre>
     * The list of fields.
     * </pre>
     *
     * <code>repeated .google.protobuf.Field fields = 2;</code>
     */
    public Builder setFields(
        int index, com.google.protobuf.Field value) {
      copyOnWrite();
      instance.setFields(index, value);
      return this;
    }
    /**
     * <pre>
     * The list of fields.
     * </pre>
     *
     * <code>repeated .google.protobuf.Field fields = 2;</code>
     */
    public Builder setFields(
        int index, com.google.protobuf.Field.Builder builderForValue) {
      copyOnWrite();
      instance.setFields(index, builderForValue);
      return this;
    }
    /**
     * <pre>
     * The list of fields.
     * </pre>
     *
     * <code>repeated .google.protobuf.Field fields = 2;</code>
     */
    public Builder addFields(com.google.protobuf.Field value) {
      copyOnWrite();
      instance.addFields(value);
      return this;
    }
    /**
     * <pre>
     * The list of fields.
     * </pre>
     *
     * <code>repeated .google.protobuf.Field fields = 2;</code>
     */
    public Builder addFields(
        int index, com.google.protobuf.Field value) {
      copyOnWrite();
      instance.addFields(index, value);
      return this;
    }
    /**
     * <pre>
     * The list of fields.
     * </pre>
     *
     * <code>repeated .google.protobuf.Field fields = 2;</code>
     */
    public Builder addFields(
        com.google.protobuf.Field.Builder builderForValue) {
      copyOnWrite();
      instance.addFields(builderForValue);
      return this;
    }
    /**
     * <pre>
     * The list of fields.
     * </pre>
     *
     * <code>repeated .google.protobuf.Field fields = 2;</code>
     */
    public Builder addFields(
        int index, com.google.protobuf.Field.Builder builderForValue) {
      copyOnWrite();
      instance.addFields(index, builderForValue);
      return this;
    }
    /**
     * <pre>
     * The list of fields.
     * </pre>
     *
     * <code>repeated .google.protobuf.Field fields = 2;</code>
     */
    public Builder addAllFields(
        java.lang.Iterable<? extends com.google.protobuf.Field> values) {
      copyOnWrite();
      instance.addAllFields(values);
      return this;
    }
    /**
     * <pre>
     * The list of fields.
     * </pre>
     *
     * <code>repeated .google.protobuf.Field fields = 2;</code>
     */
    public Builder clearFields() {
      copyOnWrite();
      instance.clearFields();
      return this;
    }
    /**
     * <pre>
     * The list of fields.
     * </pre>
     *
     * <code>repeated .google.protobuf.Field fields = 2;</code>
     */
    public Builder removeFields(int index) {
      copyOnWrite();
      instance.removeFields(index);
      return this;
    }

    /**
     * <pre>
     * The list of types appearing in `oneof` definitions in this type.
     * </pre>
     *
     * <code>repeated string oneofs = 3;</code>
     */
    public java.util.List<String>
        getOneofsList() {
      return java.util.Collections.unmodifiableList(
          instance.getOneofsList());
    }
    /**
     * <pre>
     * The list of types appearing in `oneof` definitions in this type.
     * </pre>
     *
     * <code>repeated string oneofs = 3;</code>
     */
    public int getOneofsCount() {
      return instance.getOneofsCount();
    }
    /**
     * <pre>
     * The list of types appearing in `oneof` definitions in this type.
     * </pre>
     *
     * <code>repeated string oneofs = 3;</code>
     */
    public java.lang.String getOneofs(int index) {
      return instance.getOneofs(index);
    }
    /**
     * <pre>
     * The list of types appearing in `oneof` definitions in this type.
     * </pre>
     *
     * <code>repeated string oneofs = 3;</code>
     */
    public com.google.protobuf.ByteString
        getOneofsBytes(int index) {
      return instance.getOneofsBytes(index);
    }
    /**
     * <pre>
     * The list of types appearing in `oneof` definitions in this type.
     * </pre>
     *
     * <code>repeated string oneofs = 3;</code>
     */
    public Builder setOneofs(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setOneofs(index, value);
      return this;
    }
    /**
     * <pre>
     * The list of types appearing in `oneof` definitions in this type.
     * </pre>
     *
     * <code>repeated string oneofs = 3;</code>
     */
    public Builder addOneofs(
        java.lang.String value) {
      copyOnWrite();
      instance.addOneofs(value);
      return this;
    }
    /**
     * <pre>
     * The list of types appearing in `oneof` definitions in this type.
     * </pre>
     *
     * <code>repeated string oneofs = 3;</code>
     */
    public Builder addAllOneofs(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllOneofs(values);
      return this;
    }
    /**
     * <pre>
     * The list of types appearing in `oneof` definitions in this type.
     * </pre>
     *
     * <code>repeated string oneofs = 3;</code>
     */
    public Builder clearOneofs() {
      copyOnWrite();
      instance.clearOneofs();
      return this;
    }
    /**
     * <pre>
     * The list of types appearing in `oneof` definitions in this type.
     * </pre>
     *
     * <code>repeated string oneofs = 3;</code>
     */
    public Builder addOneofsBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addOneofsBytes(value);
      return this;
    }

    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 4;</code>
     */
    public java.util.List<com.google.protobuf.Option> getOptionsList() {
      return java.util.Collections.unmodifiableList(
          instance.getOptionsList());
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 4;</code>
     */
    public int getOptionsCount() {
      return instance.getOptionsCount();
    }/**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 4;</code>
     */
    public com.google.protobuf.Option getOptions(int index) {
      return instance.getOptions(index);
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 4;</code>
     */
    public Builder setOptions(
        int index, com.google.protobuf.Option value) {
      copyOnWrite();
      instance.setOptions(index, value);
      return this;
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 4;</code>
     */
    public Builder setOptions(
        int index, com.google.protobuf.Option.Builder builderForValue) {
      copyOnWrite();
      instance.setOptions(index, builderForValue);
      return this;
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 4;</code>
     */
    public Builder addOptions(com.google.protobuf.Option value) {
      copyOnWrite();
      instance.addOptions(value);
      return this;
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 4;</code>
     */
    public Builder addOptions(
        int index, com.google.protobuf.Option value) {
      copyOnWrite();
      instance.addOptions(index, value);
      return this;
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 4;</code>
     */
    public Builder addOptions(
        com.google.protobuf.Option.Builder builderForValue) {
      copyOnWrite();
      instance.addOptions(builderForValue);
      return this;
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 4;</code>
     */
    public Builder addOptions(
        int index, com.google.protobuf.Option.Builder builderForValue) {
      copyOnWrite();
      instance.addOptions(index, builderForValue);
      return this;
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 4;</code>
     */
    public Builder addAllOptions(
        java.lang.Iterable<? extends com.google.protobuf.Option> values) {
      copyOnWrite();
      instance.addAllOptions(values);
      return this;
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 4;</code>
     */
    public Builder clearOptions() {
      copyOnWrite();
      instance.clearOptions();
      return this;
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 4;</code>
     */
    public Builder removeOptions(int index) {
      copyOnWrite();
      instance.removeOptions(index);
      return this;
    }

    /**
     * <pre>
     * The source context.
     * </pre>
     *
     * <code>optional .google.protobuf.SourceContext source_context = 5;</code>
     */
    public boolean hasSourceContext() {
      return instance.hasSourceContext();
    }
    /**
     * <pre>
     * The source context.
     * </pre>
     *
     * <code>optional .google.protobuf.SourceContext source_context = 5;</code>
     */
    public com.google.protobuf.SourceContext getSourceContext() {
      return instance.getSourceContext();
    }
    /**
     * <pre>
     * The source context.
     * </pre>
     *
     * <code>optional .google.protobuf.SourceContext source_context = 5;</code>
     */
    public Builder setSourceContext(com.google.protobuf.SourceContext value) {
      copyOnWrite();
      instance.setSourceContext(value);
      return this;
      }
    /**
     * <pre>
     * The source context.
     * </pre>
     *
     * <code>optional .google.protobuf.SourceContext source_context = 5;</code>
     */
    public Builder setSourceContext(
        com.google.protobuf.SourceContext.Builder builderForValue) {
      copyOnWrite();
      instance.setSourceContext(builderForValue);
      return this;
    }
    /**
     * <pre>
     * The source context.
     * </pre>
     *
     * <code>optional .google.protobuf.SourceContext source_context = 5;</code>
     */
    public Builder mergeSourceContext(com.google.protobuf.SourceContext value) {
      copyOnWrite();
      instance.mergeSourceContext(value);
      return this;
    }
    /**
     * <pre>
     * The source context.
     * </pre>
     *
     * <code>optional .google.protobuf.SourceContext source_context = 5;</code>
     */
    public Builder clearSourceContext() {  copyOnWrite();
      instance.clearSourceContext();
      return this;
    }

    /**
     * <pre>
     * The source syntax.
     * </pre>
     *
     * <code>optional .google.protobuf.Syntax syntax = 6;</code>
     */
    public int getSyntaxValue() {
      return instance.getSyntaxValue();
    }
    /**
     * <pre>
     * The source syntax.
     * </pre>
     *
     * <code>optional .google.protobuf.Syntax syntax = 6;</code>
     */
    public Builder setSyntaxValue(int value) {
      copyOnWrite();
      instance.setSyntaxValue(value);
      return this;
    }
    /**
     * <pre>
     * The source syntax.
     * </pre>
     *
     * <code>optional .google.protobuf.Syntax syntax = 6;</code>
     */
    public com.google.protobuf.Syntax getSyntax() {
      return instance.getSyntax();
    }
    /**
     * <pre>
     * The source syntax.
     * </pre>
     *
     * <code>optional .google.protobuf.Syntax syntax = 6;</code>
     */
    public Builder setSyntax(com.google.protobuf.Syntax value) {
      copyOnWrite();
      instance.setSyntax(value);
      return this;
    }
    /**
     * <pre>
     * The source syntax.
     * </pre>
     *
     * <code>optional .google.protobuf.Syntax syntax = 6;</code>
     */
    public Builder clearSyntax() {
      copyOnWrite();
      instance.clearSyntax();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.protobuf.Type)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.google.protobuf.Type();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        fields_.makeImmutable();
        oneofs_.makeImmutable();
        options_.makeImmutable();
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        com.google.protobuf.Type other = (com.google.protobuf.Type) arg1;
        name_ = visitor.visitString(!name_.isEmpty(), name_,
            !other.name_.isEmpty(), other.name_);
        fields_= visitor.visitList(fields_, other.fields_);
        oneofs_= visitor.visitList(oneofs_, other.oneofs_);
        options_= visitor.visitList(options_, other.options_);
        sourceContext_ = visitor.visitMessage(sourceContext_, other.sourceContext_);
        syntax_ = visitor.visitInt(syntax_ != 0, syntax_,    other.syntax_ != 0, other.syntax_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
              case 18: {
                if (!fields_.isModifiable()) {
                  fields_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(fields_);
                }
                fields_.add(
                    input.readMessage(com.google.protobuf.Field.parser(), extensionRegistry));
                break;
              }
              case 26: {
                String s = input.readStringRequireUtf8();
                if (!oneofs_.isModifiable()) {
                  oneofs_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(oneofs_);
                }
                oneofs_.add(s);
                break;
              }
              case 34: {
                if (!options_.isModifiable()) {
                  options_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(options_);
                }
                options_.add(
                    input.readMessage(com.google.protobuf.Option.parser(), extensionRegistry));
                break;
              }
              case 42: {
                com.google.protobuf.SourceContext.Builder subBuilder = null;
                if (sourceContext_ != null) {
                  subBuilder = sourceContext_.toBuilder();
                }
                sourceContext_ = input.readMessage(com.google.protobuf.SourceContext.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(sourceContext_);
                  sourceContext_ = subBuilder.buildPartial();
                }

                break;
              }
              case 48: {
                int rawValue = input.readEnum();

                syntax_ = rawValue;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (com.google.protobuf.Type.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:google.protobuf.Type)
  private static final com.google.protobuf.Type DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Type();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static com.google.protobuf.Type getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Type> PARSER;

  public static com.google.protobuf.Parser<Type> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

