// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/struct.proto

package com.google.protobuf;

public interface ValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.Value)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Represents a null value.
   * </pre>
   *
   * <code>optional .google.protobuf.NullValue null_value = 1;</code>
   */
  int getNullValueValue();
  /**
   * <pre>
   * Represents a null value.
   * </pre>
   *
   * <code>optional .google.protobuf.NullValue null_value = 1;</code>
   */
  com.google.protobuf.NullValue getNullValue();

  /**
   * <pre>
   * Represents a double value.
   * </pre>
   *
   * <code>optional double number_value = 2;</code>
   */
  double getNumberValue();

  /**
   * <pre>
   * Represents a string value.
   * </pre>
   *
   * <code>optional string string_value = 3;</code>
   */
  java.lang.String getStringValue();
  /**
   * <pre>
   * Represents a string value.
   * </pre>
   *
   * <code>optional string string_value = 3;</code>
   */
  com.google.protobuf.ByteString
      getStringValueBytes();

  /**
   * <pre>
   * Represents a boolean value.
   * </pre>
   *
   * <code>optional bool bool_value = 4;</code>
   */
  boolean getBoolValue();

  /**
   * <pre>
   * Represents a structured value.
   * </pre>
   *
   * <code>optional .google.protobuf.Struct struct_value = 5;</code>
   */
  com.google.protobuf.Struct getStructValue();

  /**
   * <pre>
   * Represents a repeated `Value`.
   * </pre>
   *
   * <code>optional .google.protobuf.ListValue list_value = 6;</code>
   */
  com.google.protobuf.ListValue getListValue();

  public com.google.protobuf.Value.KindCase getKindCase();
}
